import { useState, useEffect, useRef } from "react";
import { 
  Activity, Users, ArrowRightLeft, PlusCircle, LogOut, Sun, Moon, Lock, Award, Trophy
} from "lucide-react";
import { Match } from "./types";
import { AuthScreen } from "./components/AuthScreen";
import { AddMatchForm } from "./components/AddMatchForm";
import { MatchExplorer } from "./components/MatchExplorer";
import { PlayerStats } from "./components/PlayerStats";
import { HeadToHead } from "./components/HeadToHead";
import { RosterManager, RosterPlayer } from "./components/RosterManager";
import { PlayerInputPanel } from "./components/PlayerInputPanel";
import { TournamentStandings } from "./components/TournamentStandings";
import { clientDb } from "./firebaseClient";

const SUPABASE_SETUP_SQL = `CREATE TABLE IF NOT EXISTS matches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date text,
  match_code text,
  league text,
  total_game text,
  game_no text,
  map text,
  live_link text,
  teams jsonb,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS roster (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  role text,
  team text,
  league text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS tournaments (
  id text PRIMARY KEY,
  data jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone
);

-- MATIKAN RLS (CARA TERMUDA DAN REKOMENDASI UNTUK PREVIEW)
ALTER TABLE matches DISABLE ROW LEVEL SECURITY;
ALTER TABLE roster DISABLE ROW LEVEL SECURITY;
ALTER TABLE tournaments DISABLE ROW LEVEL SECURITY;

-- ALTERNATIF: JIKA RLS TETAP AKTIF, BUAT POLICIES IZIN UNTUK SEMUA AKSES
DROP POLICY IF EXISTS "Allow public read" ON roster;
DROP POLICY IF EXISTS "Allow public insert" ON roster;
DROP POLICY IF EXISTS "Allow public update" ON roster;
DROP POLICY IF EXISTS "Allow public delete" ON roster;

CREATE POLICY "Allow public read" ON roster FOR SELECT TO public USING (true);
CREATE POLICY "Allow public insert" ON roster FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Allow public update" ON roster FOR UPDATE TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete" ON roster FOR DELETE TO public USING (true);

DROP POLICY IF EXISTS "Allow public read" ON matches;
DROP POLICY IF EXISTS "Allow public insert" ON matches;
DROP POLICY IF EXISTS "Allow public update" ON matches;
DROP POLICY IF EXISTS "Allow public delete" ON matches;

CREATE POLICY "Allow public read" ON matches FOR SELECT TO public USING (true);
CREATE POLICY "Allow public insert" ON matches FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Allow public update" ON matches FOR UPDATE TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete" ON matches FOR DELETE TO public USING (true);

DROP POLICY IF EXISTS "Allow public read" ON tournaments;
DROP POLICY IF EXISTS "Allow public insert" ON tournaments;
DROP POLICY IF EXISTS "Allow public update" ON tournaments;
DROP POLICY IF EXISTS "Allow public delete" ON tournaments;

CREATE POLICY "Allow public read" ON tournaments FOR SELECT TO public USING (true);
CREATE POLICY "Allow public insert" ON tournaments FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Allow public update" ON tournaments FOR UPDATE TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete" ON tournaments FOR DELETE TO public USING (true);`;

export default function App() {
  // Access credentials intentionally live only in memory. A refresh locks the app again.
  const [token, setToken] = useState<string | null>(null);
  const [isDarkMode, setIsDarkMode] = useState<boolean>(() => {
    const saved = localStorage.getItem("pubgm_db_theme");
    return saved ? saved === "dark" : true;
  });
  const [activeTab, setActiveTab] = useState<string>("matches");
  
  // Data states
  const [matches, setMatches] = useState<Match[]>([]);
  const [roster, setRoster] = useState<RosterPlayer[]>([]);
  const [isLoadingMatches, setIsLoadingMatches] = useState(false);
  const [isLoadingRoster, setIsLoadingRoster] = useState(false);
  const [supabaseSetupNeeded, setSupabaseSetupNeeded] = useState(false);

  // Tournaments state synced across all tabs
  const [tournaments, setTournaments] = useState<any[]>(() => {
    const stored = localStorage.getItem("tournaments_list_v4");
    if (stored) {
      try {
        return JSON.parse(stored);
      } catch (e) {
        console.error("Failed to parse tournaments", e);
      }
    }
    const defaults = [
      {
        id: "pmsl_sea_2026",
        name: "PMSL SEA 2026",
        format: "16",
        activeMatchup: "A_B",
        activeGroup: "A",
        activeWeek: "1",
        tiebreaker: "WWCD-PlacementPoint-Kill",
        teams16Text: [
          "BOOM Esports", "Alter Ego Ares", "Talon Esports", "Bigetron Knights",
          "RRQ Ryu", "Vampire Esports", "Yoodo Alliance", "FaZe Clan",
          "D'Xavier", "Geek Fam", "Morph GPX", "Level Up Indonesia",
          "VOIN Esports", "SEM9", "Genesis Dogma", "STX Esports"
        ].join("\n"),
        groupAText: ["BOOM Esports", "Alter Ego Ares", "RRQ Ryu", "FaZe Clan", "Vampire Esports", "VOIN Esports", "SEM9", "Morph GPX"].join("\n"),
        groupBText: ["Bigetron Knights", "Talon Esports", "Geek Fam", "Yoodo Alliance", "D'Xavier", "Level Up Indonesia", "Genesis Dogma", "STX Esports"].join("\n"),
        groupCText: ["Team Liquid ID", "Fnatic Onic", "Rex Regum Qeon", "Evos Glory", "Bigetron Alpha", "Alter Ego", "Geek Fam ID", "Dewa United"].join("\n"),
        groupDText: ["VOIN Esports", "SEM9", "Genesis Dogma", "STX Esports"].join("\n"),
        groupEText: ["Team Liquid ID", "Fnatic Onic", "Rex Regum Qeon", "Evos Glory"].join("\n"),
      },
      {
        id: "pmgc_2026",
        name: "PMGC 2026",
        format: "16",
        activeMatchup: "A_B",
        activeGroup: "A",
        activeWeek: "1",
        tiebreaker: "WWCD-PlacementPoint-Kill",
        teams16Text: [
          "Reject", "D'Xavier", "Alpha7 Esports", "Vampire Esports",
          "Stalwart Esports", "Nigma Galaxy", "Nova Esports", "IHC Esports",
          "Talon Esports", "BOOM Esports", "FaZe Clan", "Loops Esports",
          "Major Pride", "Gaimin Gladiators", "S2G Esports", "Alliance"
        ].join("\n"),
        groupAText: ["Reject", "D'Xavier", "Alpha7 Esports", "Vampire Esports", "Stalwart Esports", "Nigma Galaxy", "Nova Esports", "IHC Esports"].join("\n"),
        groupBText: ["Talon Esports", "BOOM Esports", "FaZe Clan", "Loops Esports", "Major Pride", "Gaimin Gladiators", "S2G Esports", "Alliance"].join("\n"),
        groupCText: ["Team Liquid ID", "Fnatic Onic", "Rex Regum Qeon", "Evos Glory", "Bigetron Alpha", "Alter Ego", "Geek Fam ID", "Dewa United"].join("\n"),
        groupDText: ["Talon Esports", "BOOM Esports", "FaZe Clan", "Loops Esports"].join("\n"),
        groupEText: ["Major Pride", "Gaimin Gladiators", "S2G Esports", "Alliance"].join("\n"),
      },
      {
        id: "pmops_indonesia",
        name: "PMPS Indonesia",
        format: "16",
        activeMatchup: "A_B",
        activeGroup: "A",
        activeWeek: "1",
        tiebreaker: "WWCD-PlacementPoint-Kill",
        teams16Text: [
          "Bigetron Knights", "BOOM Esports", "Alter Ego Ares", "Talon Esports",
          "RRQ Ryu", "VOIN Esports", "Morph GPX", "Level Up Indonesia",
          "Geek Fam", "Kagendra", "Penta Esports", "Dewa United",
          "Onyx Esports", "Vampire Esports", "SEM9", "Aura Esports"
        ].join("\n"),
        groupAText: ["Bigetron Knights", "BOOM Esports", "Alter Ego Ares", "Talon Esports", "RRQ Ryu", "VOIN Esports", "Morph GPX", "Level Up Indonesia"].join("\n"),
        groupBText: ["Geek Fam", "Kagendra", "Penta Esports", "Dewa United", "Onyx Esports", "Vampire Esports", "SEM9", "Aura Esports"].join("\n"),
        groupCText: ["Rex Regum Qeon", "Team Liquid ID", "Evos Glory", "Fnatic Onic", "Bigetron Alpha", "Alter Ego", "Dewa United Esports", "Geek Fam ID"].join("\n"),
        groupDText: ["Geek Fam", "Kagendra", "Penta Esports", "Dewa United"].join("\n"),
        groupEText: ["Onyx Esports", "Vampire Esports", "SEM9", "Aura Esports"].join("\n"),
      },
      {
        id: "lobby_scrim",
        name: "Lobby Scrim",
        format: "16",
        activeMatchup: "A_B",
        activeGroup: "A",
        activeWeek: "1",
        tiebreaker: "WWCD-PlacementPoint-Kill",
        teams16Text: [
          "Scrim Team 1", "Scrim Team 2", "Scrim Team 3", "Scrim Team 4",
          "Scrim Team 5", "Scrim Team 6", "Scrim Team 7", "Scrim Team 8",
          "Scrim Team 9", "Scrim Team 10", "Scrim Team 11", "Scrim Team 12",
          "Scrim Team 13", "Scrim Team 14", "Scrim Team 15", "Scrim Team 16"
        ].join("\n"),
        groupAText: ["Scrim Team A1", "Scrim Team A2", "Scrim Team A3", "Scrim Team A4", "Scrim Team A5", "Scrim Team A6", "Scrim Team A7", "Scrim Team A8"].join("\n"),
        groupBText: ["Scrim Team B1", "Scrim Team B2", "Scrim Team B3", "Scrim Team B4", "Scrim Team B5", "Scrim Team B6", "Scrim Team B7", "Scrim Team B8"].join("\n"),
        groupCText: ["Scrim Team C1", "Scrim Team C2", "Scrim Team C3", "Scrim Team C4", "Scrim Team C5", "Scrim Team C6", "Scrim Team C7", "Scrim Team C8"].join("\n"),
        groupDText: ["Scrim Team D1", "Scrim Team D2", "Scrim Team D3", "Scrim Team D4"].join("\n"),
        groupEText: ["Scrim Team E1", "Scrim Team E2", "Scrim Team E3", "Scrim Team E4"].join("\n"),
      }
    ];
    localStorage.setItem("tournaments_list_v4", JSON.stringify(defaults));
    return defaults;
  });

  // Debounce ref for tournament autosave: group edits (e.g. typing team names)
  // fire onUpdateTournaments on every keystroke, so writes to the shared
  // database are batched instead of firing one request per keystroke.
  const tournamentSaveTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const persistTournaments = async (updatedTournaments: any[]) => {
    try {
      if (clientDb.getIsStatic()) {
        await clientDb.saveTournaments(updatedTournaments);
        return;
      }
      const tokenToUse = actionPassword || token || "";
      const res = await fetch("/api/tournaments", {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${tokenToUse}`
        },
        body: JSON.stringify({ tournaments: updatedTournaments })
      });
      if (!res.ok) {
        const errData = await res.json().catch(() => ({}));
        showToast(errData.error || "Gagal menyimpan turnamen ke database.", "error");
      }
    } catch (err: any) {
      try {
        await clientDb.saveTournaments(updatedTournaments);
      } catch (dbErr: any) {
        showToast("Gagal menyimpan turnamen: " + err.message, "error");
      }
    }
  };

  // Tournament/group config is shared across every browser that logs in, so
  // edits made in the admin panel need to reach the database, not just this
  // browser's localStorage. Local state + localStorage update instantly for a
  // responsive UI; the network write is debounced so rapid edits (typing a
  // team name) don't fire a request per keystroke.
  const handleUpdateTournaments = (updatedTournaments: any[]) => {
    setTournaments(updatedTournaments);
    localStorage.setItem("tournaments_list_v4", JSON.stringify(updatedTournaments));

    if (tournamentSaveTimeoutRef.current) {
      clearTimeout(tournamentSaveTimeoutRef.current);
    }
    tournamentSaveTimeoutRef.current = setTimeout(() => {
      persistTournaments(updatedTournaments);
    }, 800);
  };

  const fetchTournaments = async () => {
    if (!token) return;
    try {
      if (clientDb.getIsStatic()) {
        const data = await clientDb.getTournaments();
        if (data && data.length > 0) {
          setTournaments(data);
          localStorage.setItem("tournaments_list_v4", JSON.stringify(data));
        } else {
          // Fresh database with no tournaments yet - seed it with the current
          // (default) local list so every browser starts from the same state.
          await persistTournaments(tournaments);
        }
        return;
      }
      const res = await fetch("/api/tournaments", {
        headers: {
          Authorization: `Bearer ${token}`
        }
      });
      if (res.ok) {
        const data = await res.json();
        if (data && data.length > 0) {
          setTournaments(data);
          localStorage.setItem("tournaments_list_v4", JSON.stringify(data));
        } else {
          // Fresh database with no tournaments yet - seed it with the current
          // (default) local list so every browser starts from the same state.
          persistTournaments(tournaments);
        }
      } else {
        const errData = await res.json().catch(() => ({}));
        if (errData.error === "DATABASE_SETUP_NEEDED") {
          setSupabaseSetupNeeded(true);
        } else {
          showToast(errData.message || errData.error || "Gagal memuat data turnamen dari database.", "error");
        }
      }
    } catch (err: any) {
      try {
        const data = await clientDb.getTournaments();
        if (data && data.length > 0) {
          setTournaments(data);
          localStorage.setItem("tournaments_list_v4", JSON.stringify(data));
        } else {
          await persistTournaments(tournaments);
        }
      } catch (clientErr: any) {
        console.error("Error fetching tournaments:", err);
        showToast("Gagal memuat data turnamen dari database: " + clientErr.message, "error");
      }
    }
  };

  // Administrative verification
  const [actionPasswordVerified, setActionPasswordVerified] = useState(false);
  const [actionPassword, setActionPassword] = useState("");
  const [adminSubTab, setAdminSubTab] = useState<"playerInput" | "addMatch">("addMatch");

  // Edit match state
  const [editingMatch, setEditingMatch] = useState<Match | null>(null);

  // Deep-link target for the Player Input Panel, set when "Edit" is clicked on an already-posted
  // player stats record from the Player Stats tab.
  const [playerInputTarget, setPlayerInputTarget] = useState<{ league: string; date?: string; week?: string } | null>(null);

  const handleEditPlayerRecord = (league: string, period: { date?: string; week?: string }) => {
    setPlayerInputTarget({ league, ...period });
    setAdminSubTab("playerInput");
    setActiveTab("admin");
  };

  // Toast notifications
  const [toast, setToast] = useState<{ message: string; type: "success" | "error" | "info" } | null>(null);

  const showToast = (message: string, type: "success" | "error" | "info" = "success") => {
    setToast({ message, type });
    setTimeout(() => {
      setToast(null);
    }, 4000);
  };

  // Remove sessions created by older versions so an update also locks open tabs.
  useEffect(() => {
    localStorage.removeItem("pubgm_db_token");
    localStorage.removeItem("pubgm_action_verified");
    localStorage.removeItem("pubgm_action_password");
  }, []);

  // Sync dark mode class
  useEffect(() => {
    const root = window.document.documentElement;
    if (isDarkMode) {
      root.classList.remove("light");
      localStorage.setItem("pubgm_db_theme", "dark");
    } else {
      root.classList.add("light");
      localStorage.setItem("pubgm_db_theme", "light");
    }
  }, [isDarkMode]);

  const handleLogin = (newToken: string) => {
    setToken(newToken);
    showToast("Selamat datang! Berhasil masuk ke database.", "success");
  };

  const handleLogout = () => {
    setToken(null);
    setActionPasswordVerified(false);
    setActionPassword("");
    showToast("Berhasil keluar dari sesi.", "info");
  };

  // Fetch match and roster data from API
  const fetchMatches = async () => {
    if (!token) return;
    setIsLoadingMatches(true);
    try {
      if (clientDb.getIsStatic()) {
        const data = await clientDb.getMatches();
        setMatches(data);
        return;
      }
      const res = await fetch("/api/matches", {
        headers: {
          Authorization: `Bearer ${token}`
        }
      });
      if (res.ok) {
        const data = await res.json();
        setMatches(data);
        setSupabaseSetupNeeded(false);
      } else {
        const errData = await res.json().catch(() => ({}));
        if (res.status === 401) {
          handleLogout();
        } else {
          if (errData.error === "DATABASE_SETUP_NEEDED" || (errData.error && (errData.error.includes("schema cache") || errData.error.includes("relation")))) {
            setSupabaseSetupNeeded(true);
          }
          showToast(errData.message || errData.error || "Gagal memuat data pertandingan.", "error");
        }
      }
    } catch (err: any) {
      try {
        const data = await clientDb.getMatches();
        setMatches(data);
      } catch (clientErr: any) {
        showToast("Kesalahan jaringan: " + err.message, "error");
      }
    } finally {
      setIsLoadingMatches(false);
    }
  };

  const fetchRoster = async () => {
    if (!token) return;
    setIsLoadingRoster(true);
    try {
      if (clientDb.getIsStatic()) {
        const data = await clientDb.getRoster();
        setRoster(data);
        return;
      }
      const res = await fetch("/api/roster", {
        headers: {
          Authorization: `Bearer ${token}`
        }
      });
      if (res.ok) {
        const data = await res.json();
        setRoster(data);
        setSupabaseSetupNeeded(false);
      } else {
        const errData = await res.json().catch(() => ({}));
        if (errData.error === "DATABASE_SETUP_NEEDED" || (errData.error && (errData.error.includes("schema cache") || errData.error.includes("relation")))) {
          setSupabaseSetupNeeded(true);
        }
      }
    } catch (err: any) {
      try {
        const data = await clientDb.getRoster();
        setRoster(data);
      } catch (clientErr: any) {
        console.error("Error fetching roster:", err);
      }
    } finally {
      setIsLoadingRoster(false);
    }
  };

  useEffect(() => {
    if (token) {
      fetchMatches();
      fetchRoster();
      fetchTournaments();
    }
  }, [token]);

  // Admin Verification check
  const verifyActionPassword = async (password: string): Promise<boolean> => {
    try {
      if (clientDb.getIsStatic()) {
        const isValid = await clientDb.verifyActionPassword(password);
        if (isValid) {
          setActionPasswordVerified(true);
          setActionPassword(password);
          showToast("Verifikasi Berhasil! Mode admin aktif.", "success");
          return true;
        }
        return false;
      }
      const res = await fetch("/api/verify-action", {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ password })
      });
      if (res.ok) {
        setActionPasswordVerified(true);
        setActionPassword(password);
        showToast("Verifikasi Berhasil! Mode admin aktif.", "success");
        return true;
      }
      return false;
    } catch (err) {
      const isValid = await clientDb.verifyActionPassword(password);
      if (isValid) {
        setActionPasswordVerified(true);
        setActionPassword(password);
        showToast("Verifikasi Berhasil! Mode admin aktif.", "success");
        return true;
      }
      return false;
    }
  };

  const handleSetActionPasswordVerified = (verified: boolean) => {
    setActionPasswordVerified(verified);
    if (!verified) {
      setActionPassword("");
      showToast("Mode admin dinonaktifkan.", "info");
    }
  };

  // Save/Edit Matches
  const handleSaveMatch = async (matchData: Match) => {
    const isEdit = !!matchData.id;
    const successMessage = isEdit ? "Berhasil memperbarui data match record." : "Berhasil menambahkan data match baru ke database.";

    const saveViaClientDb = async () => {
      if (isEdit) {
        await clientDb.updateMatch(matchData.id!, matchData);
      } else {
        await clientDb.addMatch(matchData);
      }
    };

    try {
      if (clientDb.getIsStatic()) {
        await saveViaClientDb();
        showToast(successMessage, "success");
        setEditingMatch(null);
        fetchMatches();
        setActiveTab("matches");
        return;
      }

      const tokenToUse = actionPassword || token || "";
      const url = isEdit ? `/api/matches/${matchData.id}` : "/api/matches";
      const method = isEdit ? "PUT" : "POST";
      const res = await fetch(url, {
        method,
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${tokenToUse}`
        },
        body: JSON.stringify(matchData)
      });

      if (!res.ok) {
        const errData = await res.json().catch(() => ({}));
        throw new Error(errData.error || "Gagal menyimpan match.");
      }

      showToast(successMessage, "success");
      setEditingMatch(null);
      fetchMatches();
      setActiveTab("matches");
    } catch (err: any) {
      // Failures are re-thrown after this so callers (AddMatchForm, PlayerInputPanel) know the
      // save genuinely failed instead of showing a false "success" message of their own.
      try {
        await saveViaClientDb();
        showToast(`${successMessage} (Static fallback).`, "success");
        setEditingMatch(null);
        fetchMatches();
        setActiveTab("matches");
      } catch (dbErr: any) {
        showToast("Error saving match: " + err.message, "error");
        throw err;
      }
    }
  };

  // Delete Match
  const handleDeleteMatch = async (id: string) => {
    try {
      if (clientDb.getIsStatic()) {
        await clientDb.deleteMatch(id);
        showToast("Match record berhasil dihapus secara permanen.", "success");
        fetchMatches();
        return;
      }
      const tokenToUse = actionPassword || token || "";
      const res = await fetch(`/api/matches/${id}?password=${encodeURIComponent(tokenToUse)}`, {
        method: "DELETE",
        headers: {
          Authorization: `Bearer ${tokenToUse}`,
          "x-password": tokenToUse
        }
      });
      if (res.ok) {
        showToast("Match record berhasil dihapus secara permanen.", "success");
        fetchMatches();
      } else {
        const errData = await res.json();
        if (res.status === 401) {
          setActionPasswordVerified(false);
          setActionPassword("");
        }
        showToast(errData.error || "Gagal menghapus match.", "error");
      }
    } catch (err: any) {
      try {
        await clientDb.deleteMatch(id);
        showToast("Match record berhasil dihapus secara permanen.", "success");
        fetchMatches();
      } catch (dbErr: any) {
        showToast("Error deleting match: " + err.message, "error");
      }
    }
  };

  // Save / Edit Roster Player
  const handleSaveRosterPlayer = async (player: RosterPlayer) => {
    try {
      if (clientDb.getIsStatic()) {
        await clientDb.saveRosterPlayer(player);
        showToast("Roster berhasil diperbarui.", "success");
        fetchRoster();
        return;
      }
      const pass = ACTION_PASSWORD_LOCAL();
      const res = await fetch("/api/roster", {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          password: pass,
          player
        })
      });
      if (res.ok) {
        showToast("Roster berhasil diperbarui.", "success");
        fetchRoster();
      } else {
        const errData = await res.json();
        showToast(errData.error || "Gagal menyimpan roster player.", "error");
      }
    } catch (err: any) {
      try {
        await clientDb.saveRosterPlayer(player);
        showToast("Roster berhasil diperbarui.", "success");
        fetchRoster();
      } catch (dbErr: any) {
        showToast("Error saving roster: " + err.message, "error");
      }
    }
  };

  // Delete Roster Player
  const handleDeleteRosterPlayer = async (id: string) => {
    try {
      if (clientDb.getIsStatic()) {
        await clientDb.deleteRosterPlayer(id);
        showToast("Pemain berhasil dihapus dari daftar roster.", "success");
        fetchRoster();
        return;
      }
      const pass = ACTION_PASSWORD_LOCAL();
      const res = await fetch(`/api/roster/${id}?password=${encodeURIComponent(pass)}`, {
        method: "DELETE",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${pass}`,
          "x-password": pass
        },
        body: JSON.stringify({
          password: pass
        })
      });
      if (res.ok) {
        showToast("Pemain berhasil dihapus dari daftar roster.", "success");
        fetchRoster();
      } else {
        const errData = await res.json();
        if (res.status === 401) {
          setActionPasswordVerified(false);
          setActionPassword("");
        }
        showToast(errData.error || "Gagal menghapus roster player.", "error");
      }
    } catch (err: any) {
      try {
        await clientDb.deleteRosterPlayer(id);
        showToast("Pemain berhasil dihapus dari daftar roster.", "success");
        fetchRoster();
      } catch (dbErr: any) {
        showToast("Error deleting roster: " + err.message, "error");
      }
    }
  };

  // Delete Player Stats across all matches
  const handleDeletePlayerStats = async (playerName: string) => {
    try {
      const matchesToUpdate = matches.filter(m => 
        (m.teams || []).some(t => 
          (t.players || []).some(p => p.name.trim().toLowerCase() === playerName.trim().toLowerCase())
        )
      );

      if (matchesToUpdate.length === 0) {
        showToast(`Tidak ditemukan data match record untuk player ${playerName}.`, "info");
        return;
      }

      // For each match containing the player, remove them from the corresponding team
      for (const m of matchesToUpdate) {
        const updatedTeams = (m.teams || []).map(t => {
          const filteredPlayers = (t.players || []).filter(p => p.name.trim().toLowerCase() !== playerName.trim().toLowerCase());
          return {
            ...t,
            players: filteredPlayers
          };
        });

        const updatedMatch: Match = {
          ...m,
          teams: updatedTeams
        };

        if (clientDb.getIsStatic()) {
          await clientDb.updateMatch(m.id!, updatedMatch);
        } else {
          const tokenToUse = actionPassword || token || "";
          await fetch(`/api/matches/${m.id}`, {
            method: "PUT",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${tokenToUse}`
            },
            body: JSON.stringify(updatedMatch)
          });
        }
      }

      showToast(`Berhasil menghapus seluruh data stats player ${playerName} secara permanen.`, "success");
      fetchMatches();
    } catch (err: any) {
      showToast("Gagal menghapus data stats player: " + err.message, "error");
    }
  };

  const ACTION_PASSWORD_LOCAL = (): string => {
    return actionPassword;
  };

  // Edit action triggers form populator
  const handleTriggerEditMatch = (match: Match) => {
    setEditingMatch(match);
  };

  if (!token) {
    return <AuthScreen onLogin={handleLogin} isDarkMode={isDarkMode} setIsDarkMode={setIsDarkMode} />;
  }

  return (
    <div className={`min-h-screen transition-colors duration-200 selection:bg-amber-500/30 font-sans ${
      isDarkMode ? "bg-[#0b0f19] text-slate-100" : "bg-slate-50 text-slate-900"
    }`}>
      {/* HEADER SECTION */}
      <header className={`sticky top-0 z-50 backdrop-blur-md transition-all ${
        isDarkMode ? "bg-[#0b0f19]/85 border-b border-slate-900" : "bg-white/85 shadow-sm"
      }`}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <img
              src="https://www.pubgmobile.com/images/event/brandassets/down-logo1.png"
              alt="PUBG Mobile"
              className="h-10 w-10 object-contain"
            />
            <div>
              <h1 className={`font-black font-display text-sm tracking-tight flex items-center gap-1.5 uppercase ${isDarkMode ? "text-slate-100" : "text-slate-950"}`}>
                PUBGM DATABASE
              </h1>
              <p className="text-[10px] text-slate-500 font-mono tracking-wide">LEVEL UP INDONESIA</p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            {/* Theme Toggle */}
            <button
              onClick={() => setIsDarkMode(!isDarkMode)}
              className={`p-2.5 rounded-xl border cursor-pointer transition-all ${
                isDarkMode ? "bg-slate-900 border-slate-800 text-slate-400 hover:text-white" : "bg-slate-200/60 border-slate-200 text-slate-600 hover:bg-slate-200"
              }`}
            >
              {isDarkMode ? <Sun className="w-4 h-4" /> : <Moon className="w-4 h-4" />}
            </button>

            {/* Admin Button */}
            <button
              onClick={() => {
                setActiveTab("admin");
                if (editingMatch) setEditingMatch(null);
              }}
              className={`p-2.5 rounded-xl border font-bold text-xs cursor-pointer transition-all flex items-center gap-1.5 ${
                activeTab === "admin"
                  ? "bg-amber-500 border-amber-400 text-slate-950"
                  : isDarkMode
                    ? "bg-slate-900 border-slate-800 text-slate-400 hover:text-white"
                    : "bg-slate-200/60 border-slate-200 text-slate-600 hover:bg-slate-200"
              }`}
            >
              <span className="font-mono">Admin</span>
            </button>

            {/* Logout button */}
            <button
              onClick={handleLogout}
              className={`p-2.5 rounded-xl border font-semibold text-xs cursor-pointer transition-all flex items-center gap-1.5 ${
                isDarkMode ? "bg-slate-900 border-slate-800 text-slate-400 hover:text-white" : "bg-slate-200/60 border-slate-200 text-slate-600 hover:bg-slate-200"
              }`}
            >
              <LogOut className="w-4 h-4 shrink-0" />
              <span className="hidden sm:inline font-mono">Sign Out</span>
            </button>
          </div>
        </div>
      </header>

      {/* CORE NAVIGATION NAVIGATION TABS */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-6">
        <div className={`p-4 rounded-3xl border transition-all ${
          isDarkMode ? "bg-slate-900/30 border-slate-900" : "bg-white border-slate-200 shadow-sm"
        }`}>
          <div className="flex items-center gap-1.5 overflow-x-auto pb-1 scrollbar-thin whitespace-nowrap">
            {[
              { id: "matches", label: "Match Records", icon: Activity },
              { id: "tournamentStandings", label: "Standings", icon: Trophy },
              { id: "playerStats", label: "Player Stats", icon: Users },
              { id: "rosterManager", label: "Squad Rosters", icon: Award },
              { id: "headTohead", label: "Tactical Comparisons", icon: ArrowRightLeft }
            ].map((tab) => {
              const Icon = tab.icon;
              const isActive = activeTab === tab.id;
              return (
                <button
                  key={tab.id}
                  onClick={() => {
                    setActiveTab(tab.id);
                    if (editingMatch) setEditingMatch(null);
                  }}
                  className={`px-4 py-2 rounded-xl font-mono text-xs font-bold transition-all flex items-center gap-2 shrink-0 cursor-pointer border ${
                    isActive
                      ? "bg-amber-500 text-slate-950 border-amber-400 shadow-md shadow-amber-500/10 font-extrabold"
                      : isDarkMode
                        ? "bg-slate-950/40 border-slate-850 text-slate-400 hover:text-white hover:bg-slate-800/40"
                        : "bg-slate-100 border-slate-200 text-slate-600 hover:text-slate-900 hover:bg-white"
                  }`}
                >
                  <Icon className="w-3.5 h-3.5 shrink-0" />
                  <span>{tab.label}</span>
                </button>
              );
            })}
          </div>
        </div>
      </div>

      {/* MAIN CONTAINER CONTENT */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {supabaseSetupNeeded && (
          <div className={`mb-8 p-6 rounded-3xl border transition-all ${
            isDarkMode ? "bg-amber-950/20 border-amber-500/30 text-amber-100" : "bg-amber-50 border-amber-200 text-amber-900"
          }`}>
            <div className="flex flex-col lg:flex-row gap-5 items-start justify-between">
              <div className="space-y-2 flex-1">
                <h3 className="font-bold text-base flex items-center gap-2">
                  <Trophy className="w-5 h-5 text-amber-500 animate-pulse" />
                  Inisialisasi Database Supabase Diperlukan
                </h3>
                <p className="text-xs text-slate-400 leading-relaxed">
                  Tabel <code className="font-mono bg-slate-900 px-1 py-0.5 rounded text-amber-400">matches</code> dan <code className="font-mono bg-slate-900 px-1 py-0.5 rounded text-amber-400">roster</code> belum terdeteksi di database Supabase Anda. 
                  Silakan salin script SQL di bawah ini, jalankan di <strong>SQL Editor</strong> dasbor Supabase Anda, lalu segarkan halaman ini.
                </p>
                <div className="mt-4 relative bg-slate-950 p-4 rounded-xl border border-slate-850 font-mono text-[11px] text-slate-300 max-h-48 overflow-y-auto whitespace-pre select-all">
                  {SUPABASE_SETUP_SQL}
                </div>
              </div>
              <button
                onClick={() => {
                  navigator.clipboard.writeText(SUPABASE_SETUP_SQL);
                  showToast("Script SQL berhasil disalin!", "success");
                }}
                className="px-4 py-2.5 rounded-xl bg-amber-500 text-slate-950 font-mono text-xs font-bold hover:bg-amber-400 cursor-pointer shadow-md shadow-amber-500/10 shrink-0 self-start lg:self-center"
              >
                Salin Script SQL
              </button>
            </div>
          </div>
        )}

        {/* Matches lists logs tab */}
        {activeTab === "matches" && (
          <MatchExplorer
            matches={matches}
            isLoading={isLoadingMatches}
            onDeleteMatch={handleDeleteMatch}
            onEditMatch={handleTriggerEditMatch}
            isDarkMode={isDarkMode}
            actionPasswordVerified={actionPasswordVerified}
          />
        )}

        {/* Tournament Standings tab */}
        {activeTab === "tournamentStandings" && (
          <TournamentStandings matches={matches} isDarkMode={isDarkMode} tournaments={tournaments} />
        )}

        {/* Player Stats Dashboard tab */}
        {activeTab === "playerStats" && (
          <PlayerStats
            matches={matches}
            isDarkMode={isDarkMode}
            actionPasswordVerified={actionPasswordVerified}
            verifyActionPassword={verifyActionPassword}
            onDeletePlayerStats={handleDeletePlayerStats}
            tournaments={tournaments}
            onEditPlayerRecord={handleEditPlayerRecord}
          />
        )}

        {/* Head-to-Head Comparison tab */}
        {activeTab === "headTohead" && (
          <HeadToHead matches={matches} isDarkMode={isDarkMode} />
        )}

        {/* Roster management database tab */}
        {activeTab === "rosterManager" && (
          <RosterManager
            roster={roster}
            matches={matches}
            isLoading={isLoadingRoster}
            onSavePlayer={handleSaveRosterPlayer}
            onDeletePlayer={handleDeleteRosterPlayer}
            isDarkMode={isDarkMode}
            verifyActionPassword={verifyActionPassword}
            actionPasswordVerified={actionPasswordVerified}
            setActionPasswordVerified={handleSetActionPasswordVerified}
            tournaments={tournaments}
            onUpdateTournaments={handleUpdateTournaments}
          />
        )}

        {/* Unified Admin Panel */}
        {activeTab === "admin" && (
          !actionPasswordVerified ? (
            <div className={`p-8 rounded-3xl max-w-sm mx-auto text-center font-mono my-12 transition-all ${
              isDarkMode ? "bg-slate-900/60 border border-slate-800" : "bg-white shadow-xl shadow-slate-100/80"
            }`}>
              <div className="inline-flex p-4 rounded-3xl bg-amber-500/10 text-amber-500 mb-4 animate-bounce">
                <Lock className="w-6 h-6" />
              </div>
              <h3 className={`text-base font-bold uppercase tracking-tight ${isDarkMode ? "text-slate-100" : "text-slate-900"}`}>Akses Dibatasi</h3>
              <p className="text-[10px] text-slate-400 mt-2 mb-6 leading-relaxed uppercase">
                Halaman ini memerlukan password aksi untuk diakses.
              </p>
              <form onSubmit={async (e) => {
                e.preventDefault();
                const formEl = e.currentTarget;
                const inputEl = formEl.elements.namedItem("actionPassword") as HTMLInputElement;
                const isOk = await verifyActionPassword(inputEl.value);
                if (!isOk) {
                  showToast("Password aksi salah!", "error");
                }
              }} className="space-y-4">
                <input
                  type="password"
                  name="actionPassword"
                  placeholder="Password Aksi"
                  className={`w-full rounded-xl py-2.5 px-4 text-center text-sm font-mono focus:outline-none focus:ring-1 focus:ring-amber-500 transition-all ${
                    isDarkMode 
                      ? "bg-slate-950 border border-slate-800 text-slate-100" 
                      : "bg-slate-100 text-slate-900"
                  }`}
                  required
                />
                <button
                  type="submit"
                  className="w-full py-2.5 px-4 rounded-xl bg-amber-500 hover:bg-amber-400 active:bg-amber-600 text-slate-950 font-bold text-xs tracking-wide transition-all shadow-lg cursor-pointer"
                >
                  UNLOCK ACCESS
                </button>
              </form>
            </div>
          ) : (
            <div className="space-y-6">
              {/* Internal Sub-Tabs for Admin Console */}
              <div className={`p-3 rounded-2xl border flex flex-wrap gap-2 transition-all ${
                isDarkMode ? "bg-slate-950 border-slate-850" : "bg-slate-50 border-slate-200"
              }`}>
                <button
                  type="button"
                  onClick={() => setAdminSubTab("addMatch")}
                  className={`px-4 py-2 text-xs font-bold font-mono rounded-xl transition-all cursor-pointer border flex items-center gap-1.5 ${
                    adminSubTab === "addMatch"
                      ? "bg-amber-500 border-amber-400 text-slate-950 shadow-md"
                      : isDarkMode
                        ? "bg-slate-900 border-slate-800 text-slate-400 hover:text-white"
                        : "bg-white border-slate-200 text-slate-600 hover:text-slate-900"
                  }`}
                >
                  <PlusCircle className="w-3.5 h-3.5 shrink-0" />
                  <span>TAMBAH DATA MATCH BARU</span>
                </button>
                <button
                  type="button"
                  onClick={() => setAdminSubTab("playerInput")}
                  className={`px-4 py-2 text-xs font-bold font-mono rounded-xl transition-all cursor-pointer border flex items-center gap-1.5 ${
                    adminSubTab === "playerInput"
                      ? "bg-amber-500 border-amber-400 text-slate-950 shadow-md"
                      : isDarkMode
                        ? "bg-slate-900 border-slate-800 text-slate-400 hover:text-white"
                        : "bg-white border-slate-200 text-slate-600 hover:text-slate-900"
                  }`}
                >
                  <Users className="w-3.5 h-3.5 shrink-0" />
                  <span>TAMBAH DATA PLAYER BARU</span>
                </button>
              </div>

              {adminSubTab === "playerInput" ? (
                <PlayerInputPanel
                  matches={matches}
                  roster={roster}
                  onSaveMatch={handleSaveMatch}
                  isDarkMode={isDarkMode}
                  tournaments={tournaments}
                  onUpdateTournaments={handleUpdateTournaments}
                  presetSelection={playerInputTarget}
                  onConsumedPresetSelection={() => setPlayerInputTarget(null)}
                />
              ) : (
                <AddMatchForm
                  onSave={handleSaveMatch}
                  onClose={() => { setEditingMatch(null); setActiveTab("matches"); }}
                  isDarkMode={isDarkMode}
                  editingMatch={null}
                  matches={matches}
                  tournaments={tournaments}
                  onUpdateTournaments={handleUpdateTournaments}
                />
              )}
            </div>
          )
        )}
      </main>

      {/* EDIT MATCH POPUP MODAL */}
      {editingMatch && (
        <div className="fixed inset-0 z-[150] flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm overflow-y-auto animate-fadeIn">
          <div className={`w-full max-w-4xl max-h-[90vh] overflow-y-auto rounded-2xl shadow-2xl border ${
            isDarkMode ? "bg-slate-900 border-slate-800" : "bg-white border-slate-200"
          }`}>
            <AddMatchForm
              onSave={handleSaveMatch}
              onClose={() => setEditingMatch(null)}
              isDarkMode={isDarkMode}
              editingMatch={editingMatch}
              matches={matches}
              tournaments={tournaments}
              onUpdateTournaments={handleUpdateTournaments}
            />
          </div>
        </div>
      )}

      {/* TOAST ALERT NOTIFICATION COMPONENT */}
      {toast && (
        <div className="fixed bottom-5 right-5 z-[200] max-w-sm animate-fadeIn">
          <div className={`border rounded-xl px-4 py-3.5 shadow-xl font-mono text-xs flex items-center gap-3 ${
            toast.type === "success" 
              ? "bg-emerald-950/95 border-emerald-500 text-emerald-400" 
              : toast.type === "error" 
                ? "bg-red-950/95 border-red-500 text-red-400" 
                : "bg-slate-900/95 border-amber-500 text-amber-500"
          }`}>
            <div className="shrink-0 p-1 bg-white/10 rounded-lg">
              <Activity className="w-4 h-4" />
            </div>
            <p className="font-semibold leading-normal">{toast.message}</p>
          </div>
        </div>
      )}
    </div>
  );
}
