import { useState, useEffect, useRef, useMemo } from "react";
import {
  Activity, Users, ArrowRightLeft, PlusCircle, LogOut, Sun, Moon, Lock, Award, Trophy, MapPin, Globe2
} from "lucide-react";
import { Match, ScheduleEntry, DailyStatsEntry } from "./types";
import { AuthScreen } from "./components/AuthScreen";
import { AddMatchForm } from "./components/AddMatchForm";
import { MatchExplorer } from "./components/MatchExplorer";
import { PlayerStats } from "./components/PlayerStats";
import { HeadToHead } from "./components/HeadToHead";
import { RosterManager, RosterPlayer } from "./components/RosterManager";
import { PlayerInputPanel } from "./components/PlayerInputPanel";
import { TournamentStandings } from "./components/TournamentStandings";
import { PmgcRace } from "./components/PmgcRace";
import { DropZoneSimulator } from "./components/DropZoneSimulator";
import { MatchSchedule } from "./components/MatchSchedule";
import { clientDb } from "./firebaseClient";
import { setSupabaseAdminSecret } from "./supabaseBrowserClient";
import { isoToGmt7Parts, gmt7ToIso } from "./utils";

const SUPABASE_SETUP_SQL = `CREATE TABLE IF NOT EXISTS matches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date text,
  match_time text,
  match_code text,
  league text,
  total_game text,
  game_no text,
  map text,
  patch text,
  live_link text,
  teams jsonb,
  is_grand_final boolean DEFAULT false,
  is_survival_stage boolean DEFAULT false,
  is_last_chance_qualifier boolean DEFAULT false,
  custom_columns jsonb,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone
);

-- Safe to re-run on a database created before this update: adds any columns above
-- that don't exist yet without touching existing rows/data.
ALTER TABLE matches ADD COLUMN IF NOT EXISTS patch text;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS is_grand_final boolean DEFAULT false;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS is_survival_stage boolean DEFAULT false;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS is_last_chance_qualifier boolean DEFAULT false;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS match_time text;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS custom_columns jsonb;

-- Player Input Panel's daily/weekly/tournament-wide aggregated stats entries live in their own
-- table, kept separate from real match results in "matches".
CREATE TABLE IF NOT EXISTS daily_stats (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  league text,
  match_code text,
  date text,
  teams jsonb,
  custom_columns jsonb,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone
);

CREATE OR REPLACE FUNCTION reset_daily_stats_id_seq() RETURNS void AS $$
BEGIN
  PERFORM setval(pg_get_serial_sequence('daily_stats', 'id'), COALESCE((SELECT MAX(id) FROM daily_stats), 0) + 1, false);
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS roster (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  role text,
  team text,
  league text,
  previous_names jsonb,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone
);

-- Safe to re-run on a database created before this update.
ALTER TABLE roster ADD COLUMN IF NOT EXISTS previous_names jsonb;

-- Reclaim deleted IDs: after deleting the highest-numbered row, the next insert reuses that ID
-- instead of skipping ahead (Postgres identity columns never do this on their own). Called by the
-- app right after every delete on these tables - harmless no-op if the deleted row wasn't the max.
CREATE OR REPLACE FUNCTION reset_matches_id_seq() RETURNS void AS $$
BEGIN
  PERFORM setval(pg_get_serial_sequence('matches', 'id'), COALESCE((SELECT MAX(id) FROM matches), 0) + 1, false);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION reset_roster_id_seq() RETURNS void AS $$
BEGIN
  PERFORM setval(pg_get_serial_sequence('roster', 'id'), COALESCE((SELECT MAX(id) FROM roster), 0) + 1, false);
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS tournaments (
  id text PRIMARY KEY,
  data jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS schedules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  league text,
  match_code text,
  game_no text,
  teams jsonb,
  map text,
  scheduled_at timestamp with time zone,
  live_link text,
  is_finished boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Safe to re-run on a database created before this update.
ALTER TABLE schedules ADD COLUMN IF NOT EXISTS game_no text;

CREATE OR REPLACE FUNCTION reset_schedules_id_seq() RETURNS void AS $$
BEGIN
  PERFORM setval(pg_get_serial_sequence('schedules', 'id'), COALESCE((SELECT MAX(id) FROM schedules), 0) + 1, false);
END;
$$ LANGUAGE plpgsql;

-- SECURITY: Row Level Security. Read stays public (the site needs to display data to visitors),
-- but every insert/update/delete now requires an "x-admin-secret" request header matching the
-- value below - checked by is_admin_request(). The app (supabaseBrowserClient.ts) sends this
-- header automatically once the action password is verified, so normal usage doesn't change.
-- >>> REPLACE 'CHANGE_ME_TO_YOUR_ACTION_PASSWORD' BELOW WITH YOUR REAL ACTION_PASSWORD / <<<
-- >>> VITE_ACTION_PASSWORD VALUE BEFORE RUNNING THIS.                                     <<<
-- Note the honest limit: this app has no real backend in production (GitHub Pages static
-- hosting), so that same value still ships inside the public JS bundle, same as it already does
-- for the UI's password prompt. This stops casual/automated tampering (anyone who just copies the
-- anon key and calls the API directly, which is what was possible before this), it does not make
-- writes unguessable to someone who deliberately digs through the bundle for it. Real protection
-- against a targeted attacker requires moving to Supabase Auth-based RLS instead.
CREATE OR REPLACE FUNCTION is_admin_request() RETURNS boolean AS $$
  SELECT current_setting('request.headers', true)::json->>'x-admin-secret' = 'CHANGE_ME_TO_YOUR_ACTION_PASSWORD';
$$ LANGUAGE sql STABLE;

ALTER TABLE matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE roster ENABLE ROW LEVEL SECURITY;
ALTER TABLE tournaments ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_stats ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read" ON roster;
DROP POLICY IF EXISTS "Allow public insert" ON roster;
DROP POLICY IF EXISTS "Allow public update" ON roster;
DROP POLICY IF EXISTS "Allow public delete" ON roster;

CREATE POLICY "Public read" ON roster FOR SELECT TO public USING (true);
CREATE POLICY "Admin insert" ON roster FOR INSERT TO public WITH CHECK (is_admin_request());
CREATE POLICY "Admin update" ON roster FOR UPDATE TO public USING (is_admin_request()) WITH CHECK (is_admin_request());
CREATE POLICY "Admin delete" ON roster FOR DELETE TO public USING (is_admin_request());

DROP POLICY IF EXISTS "Allow public read" ON matches;
DROP POLICY IF EXISTS "Allow public insert" ON matches;
DROP POLICY IF EXISTS "Allow public update" ON matches;
DROP POLICY IF EXISTS "Allow public delete" ON matches;

CREATE POLICY "Public read" ON matches FOR SELECT TO public USING (true);
CREATE POLICY "Admin insert" ON matches FOR INSERT TO public WITH CHECK (is_admin_request());
CREATE POLICY "Admin update" ON matches FOR UPDATE TO public USING (is_admin_request()) WITH CHECK (is_admin_request());
CREATE POLICY "Admin delete" ON matches FOR DELETE TO public USING (is_admin_request());

DROP POLICY IF EXISTS "Allow public read" ON tournaments;
DROP POLICY IF EXISTS "Allow public insert" ON tournaments;
DROP POLICY IF EXISTS "Allow public update" ON tournaments;
DROP POLICY IF EXISTS "Allow public delete" ON tournaments;

CREATE POLICY "Public read" ON tournaments FOR SELECT TO public USING (true);
CREATE POLICY "Admin insert" ON tournaments FOR INSERT TO public WITH CHECK (is_admin_request());
CREATE POLICY "Admin update" ON tournaments FOR UPDATE TO public USING (is_admin_request()) WITH CHECK (is_admin_request());
CREATE POLICY "Admin delete" ON tournaments FOR DELETE TO public USING (is_admin_request());

DROP POLICY IF EXISTS "Allow public read" ON schedules;
DROP POLICY IF EXISTS "Allow public insert" ON schedules;
DROP POLICY IF EXISTS "Allow public update" ON schedules;
DROP POLICY IF EXISTS "Allow public delete" ON schedules;

CREATE POLICY "Public read" ON schedules FOR SELECT TO public USING (true);
CREATE POLICY "Admin insert" ON schedules FOR INSERT TO public WITH CHECK (is_admin_request());
CREATE POLICY "Admin update" ON schedules FOR UPDATE TO public USING (is_admin_request()) WITH CHECK (is_admin_request());
CREATE POLICY "Admin delete" ON schedules FOR DELETE TO public USING (is_admin_request());

DROP POLICY IF EXISTS "Allow public read" ON daily_stats;
DROP POLICY IF EXISTS "Allow public insert" ON daily_stats;
DROP POLICY IF EXISTS "Allow public update" ON daily_stats;
DROP POLICY IF EXISTS "Allow public delete" ON daily_stats;

CREATE POLICY "Public read" ON daily_stats FOR SELECT TO public USING (true);
CREATE POLICY "Admin insert" ON daily_stats FOR INSERT TO public WITH CHECK (is_admin_request());
CREATE POLICY "Admin update" ON daily_stats FOR UPDATE TO public USING (is_admin_request()) WITH CHECK (is_admin_request());
CREATE POLICY "Admin delete" ON daily_stats FOR DELETE TO public USING (is_admin_request());`;

export default function App() {
  // Access credentials intentionally live only in memory. A refresh locks the app again.
  const [token, setToken] = useState<string | null>(null);
  const [isDarkMode, setIsDarkMode] = useState<boolean>(() => {
    const saved = localStorage.getItem("pubgm_db_theme");
    return saved ? saved === "dark" : true;
  });
  const [activeTab, setActiveTab] = useState<string>("matches");
  
  // Data states
  const [matches, setMatches] = useState<Match[]>([]);
  const [roster, setRoster] = useState<RosterPlayer[]>([]);
  const [schedules, setSchedules] = useState<ScheduleEntry[]>([]);
  const [dailyStats, setDailyStats] = useState<DailyStatsEntry[]>([]);
  const [isLoadingMatches, setIsLoadingMatches] = useState(false);
  const [isLoadingRoster, setIsLoadingRoster] = useState(false);
  const [isLoadingSchedules, setIsLoadingSchedules] = useState(false);
  const [supabaseSetupNeeded, setSupabaseSetupNeeded] = useState(false);

  // Tournaments state synced across all tabs
  const [tournaments, setTournaments] = useState<any[]>(() => {
    const stored = localStorage.getItem("tournaments_list_v4");
    if (stored) {
      try {
        return JSON.parse(stored);
      } catch (e) {
        console.error("Failed to parse tournaments", e);
      }
    }
    const defaults = [
      {
        id: "pmsl_sea_2026",
        name: "PMSL SEA 2026",
        format: "16",
        activeMatchup: "A_B",
        activeGroup: "A",
        activeWeek: "1",
        tiebreaker: "WWCD-PlacementPoint-Kill",
        teams16Text: [
          "BOOM Esports", "Alter Ego Ares", "Talon Esports", "Bigetron Knights",
          "RRQ Ryu", "Vampire Esports", "Yoodo Alliance", "FaZe Clan",
          "D'Xavier", "Geek Fam", "Morph GPX", "Level Up Indonesia",
          "VOIN Esports", "SEM9", "Genesis Dogma", "STX Esports"
        ].join("\n"),
        groupAText: ["BOOM Esports", "Alter Ego Ares", "RRQ Ryu", "FaZe Clan", "Vampire Esports", "VOIN Esports", "SEM9", "Morph GPX"].join("\n"),
        groupBText: ["Bigetron Knights", "Talon Esports", "Geek Fam", "Yoodo Alliance", "D'Xavier", "Level Up Indonesia", "Genesis Dogma", "STX Esports"].join("\n"),
        groupCText: ["Team Liquid ID", "Fnatic Onic", "Rex Regum Qeon", "Evos Glory", "Bigetron Alpha", "Alter Ego", "Geek Fam ID", "Dewa United"].join("\n"),
        groupDText: ["VOIN Esports", "SEM9", "Genesis Dogma", "STX Esports"].join("\n"),
        groupEText: ["Team Liquid ID", "Fnatic Onic", "Rex Regum Qeon", "Evos Glory"].join("\n"),
      },
      {
        id: "pmgc_2026",
        name: "PMGC 2026",
        format: "16",
        activeMatchup: "A_B",
        activeGroup: "A",
        activeWeek: "1",
        tiebreaker: "WWCD-PlacementPoint-Kill",
        teams16Text: [
          "Reject", "D'Xavier", "Alpha7 Esports", "Vampire Esports",
          "Stalwart Esports", "Nigma Galaxy", "Nova Esports", "IHC Esports",
          "Talon Esports", "BOOM Esports", "FaZe Clan", "Loops Esports",
          "Major Pride", "Gaimin Gladiators", "S2G Esports", "Alliance"
        ].join("\n"),
        groupAText: ["Reject", "D'Xavier", "Alpha7 Esports", "Vampire Esports", "Stalwart Esports", "Nigma Galaxy", "Nova Esports", "IHC Esports"].join("\n"),
        groupBText: ["Talon Esports", "BOOM Esports", "FaZe Clan", "Loops Esports", "Major Pride", "Gaimin Gladiators", "S2G Esports", "Alliance"].join("\n"),
        groupCText: ["Team Liquid ID", "Fnatic Onic", "Rex Regum Qeon", "Evos Glory", "Bigetron Alpha", "Alter Ego", "Geek Fam ID", "Dewa United"].join("\n"),
        groupDText: ["Talon Esports", "BOOM Esports", "FaZe Clan", "Loops Esports"].join("\n"),
        groupEText: ["Major Pride", "Gaimin Gladiators", "S2G Esports", "Alliance"].join("\n"),
      },
      {
        id: "pmops_indonesia",
        name: "PMPS Indonesia",
        format: "16",
        activeMatchup: "A_B",
        activeGroup: "A",
        activeWeek: "1",
        tiebreaker: "WWCD-PlacementPoint-Kill",
        teams16Text: [
          "Bigetron Knights", "BOOM Esports", "Alter Ego Ares", "Talon Esports",
          "RRQ Ryu", "VOIN Esports", "Morph GPX", "Level Up Indonesia",
          "Geek Fam", "Kagendra", "Penta Esports", "Dewa United",
          "Onyx Esports", "Vampire Esports", "SEM9", "Aura Esports"
        ].join("\n"),
        groupAText: ["Bigetron Knights", "BOOM Esports", "Alter Ego Ares", "Talon Esports", "RRQ Ryu", "VOIN Esports", "Morph GPX", "Level Up Indonesia"].join("\n"),
        groupBText: ["Geek Fam", "Kagendra", "Penta Esports", "Dewa United", "Onyx Esports", "Vampire Esports", "SEM9", "Aura Esports"].join("\n"),
        groupCText: ["Rex Regum Qeon", "Team Liquid ID", "Evos Glory", "Fnatic Onic", "Bigetron Alpha", "Alter Ego", "Dewa United Esports", "Geek Fam ID"].join("\n"),
        groupDText: ["Geek Fam", "Kagendra", "Penta Esports", "Dewa United"].join("\n"),
        groupEText: ["Onyx Esports", "Vampire Esports", "SEM9", "Aura Esports"].join("\n"),
      },
      {
        id: "lobby_scrim",
        name: "Lobby Scrim",
        format: "16",
        activeMatchup: "A_B",
        activeGroup: "A",
        activeWeek: "1",
        tiebreaker: "WWCD-PlacementPoint-Kill",
        teams16Text: [
          "Scrim Team 1", "Scrim Team 2", "Scrim Team 3", "Scrim Team 4",
          "Scrim Team 5", "Scrim Team 6", "Scrim Team 7", "Scrim Team 8",
          "Scrim Team 9", "Scrim Team 10", "Scrim Team 11", "Scrim Team 12",
          "Scrim Team 13", "Scrim Team 14", "Scrim Team 15", "Scrim Team 16"
        ].join("\n"),
        groupAText: ["Scrim Team A1", "Scrim Team A2", "Scrim Team A3", "Scrim Team A4", "Scrim Team A5", "Scrim Team A6", "Scrim Team A7", "Scrim Team A8"].join("\n"),
        groupBText: ["Scrim Team B1", "Scrim Team B2", "Scrim Team B3", "Scrim Team B4", "Scrim Team B5", "Scrim Team B6", "Scrim Team B7", "Scrim Team B8"].join("\n"),
        groupCText: ["Scrim Team C1", "Scrim Team C2", "Scrim Team C3", "Scrim Team C4", "Scrim Team C5", "Scrim Team C6", "Scrim Team C7", "Scrim Team C8"].join("\n"),
        groupDText: ["Scrim Team D1", "Scrim Team D2", "Scrim Team D3", "Scrim Team D4"].join("\n"),
        groupEText: ["Scrim Team E1", "Scrim Team E2", "Scrim Team E3", "Scrim Team E4"].join("\n"),
      }
    ];
    localStorage.setItem("tournaments_list_v4", JSON.stringify(defaults));
    return defaults;
  });

  // Debounce ref for tournament autosave: group edits (e.g. typing team names)
  // fire onUpdateTournaments on every keystroke, so writes to the shared
  // database are batched instead of firing one request per keystroke.
  const tournamentSaveTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const persistTournaments = async (updatedTournaments: any[]) => {
    try {
      if (clientDb.getIsStatic()) {
        await clientDb.saveTournaments(updatedTournaments);
        return;
      }
      const tokenToUse = actionPassword || token || "";
      const res = await fetch("/api/tournaments", {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${tokenToUse}`
        },
        body: JSON.stringify({ tournaments: updatedTournaments })
      });
      if (!res.ok) {
        const errData = await res.json().catch(() => ({}));
        showToast(errData.error || "Failed to save tournament to the database.", "error");
      }
    } catch (err: any) {
      try {
        await clientDb.saveTournaments(updatedTournaments);
      } catch (dbErr: any) {
        showToast("Failed to save tournament: " + err.message, "error");
      }
    }
  };

  // Tournament/group config is shared across every browser that logs in, so
  // edits made in the admin panel need to reach the database, not just this
  // browser's localStorage. Local state + localStorage update instantly for a
  // responsive UI; the network write is debounced so rapid edits (typing a
  // team name) don't fire a request per keystroke.
  const handleUpdateTournaments = (updatedTournaments: any[]) => {
    setTournaments(updatedTournaments);
    localStorage.setItem("tournaments_list_v4", JSON.stringify(updatedTournaments));

    if (tournamentSaveTimeoutRef.current) {
      clearTimeout(tournamentSaveTimeoutRef.current);
    }
    tournamentSaveTimeoutRef.current = setTimeout(() => {
      persistTournaments(updatedTournaments);
    }, 800);
  };

  const fetchTournaments = async () => {
    if (!token) return;
    try {
      if (clientDb.getIsStatic()) {
        const data = await clientDb.getTournaments();
        if (data && data.length > 0) {
          setTournaments(data);
          localStorage.setItem("tournaments_list_v4", JSON.stringify(data));
        } else {
          // Fresh database with no tournaments yet - seed it with the current
          // (default) local list so every browser starts from the same state.
          await persistTournaments(tournaments);
        }
        return;
      }
      const res = await fetch("/api/tournaments", {
        headers: {
          Authorization: `Bearer ${token}`
        }
      });
      if (res.ok) {
        const data = await res.json();
        if (data && data.length > 0) {
          setTournaments(data);
          localStorage.setItem("tournaments_list_v4", JSON.stringify(data));
        } else {
          // Fresh database with no tournaments yet - seed it with the current
          // (default) local list so every browser starts from the same state.
          persistTournaments(tournaments);
        }
      } else {
        const errData = await res.json().catch(() => ({}));
        if (errData.error === "DATABASE_SETUP_NEEDED") {
          setSupabaseSetupNeeded(true);
        } else {
          showToast(errData.message || errData.error || "Failed to load tournament data from the database.", "error");
        }
      }
    } catch (err: any) {
      try {
        const data = await clientDb.getTournaments();
        if (data && data.length > 0) {
          setTournaments(data);
          localStorage.setItem("tournaments_list_v4", JSON.stringify(data));
        } else {
          await persistTournaments(tournaments);
        }
      } catch (clientErr: any) {
        console.error("Error fetching tournaments:", err);
        showToast("Failed to load tournament data from the database: " + clientErr.message, "error");
      }
    }
  };

  // Administrative verification
  const [actionPasswordVerified, setActionPasswordVerified] = useState(false);
  const [actionPassword, setActionPassword] = useState("");
  const [adminSubTab, setAdminSubTab] = useState<"playerInput" | "addMatch">("addMatch");

  // Keeps the Supabase browser client's "x-admin-secret" header (see supabaseBrowserClient.ts and
  // is_admin_request(), see SUPABASE_SETUP_SQL above) in sync with whatever action password is currently
  // held, in static/GitHub Pages mode - a single source of truth instead of updating it at every
  // individual setActionPassword call site.
  useEffect(() => {
    setSupabaseAdminSecret(actionPassword);
  }, [actionPassword]);

  // Edit match state
  const [editingMatch, setEditingMatch] = useState<Match | null>(null);

  // Deep-link from a Match Schedule entry's "Enter Match Result" button into Add New Match Data,
  // so the league/map/date/title don't have to be retyped after already being set on the schedule.
  // scheduleToFinishOnSaveId is remembered so that once the resulting match saves successfully,
  // that schedule entry is automatically flipped to Finished - no separate manual step needed.
  const [matchPrefill, setMatchPrefill] = useState<{ league?: string; map?: string; date?: string; time?: string; matchCode?: string; gameNo?: string; isGrandFinal?: boolean; isSurvivalStage?: boolean; isLastChanceQualifier?: boolean } | null>(null);
  const [scheduleToFinishOnSaveId, setScheduleToFinishOnSaveId] = useState<string | null>(null);

  const handleEnterScheduleResults = (schedule: ScheduleEntry) => {
    const gmt7Parts = isoToGmt7Parts(schedule.scheduledAt);
    setMatchPrefill({
      league: schedule.league,
      map: schedule.map,
      date: gmt7Parts?.date,
      time: gmt7Parts?.time,
      matchCode: schedule.matchCode,
      gameNo: schedule.gameNo,
      isGrandFinal: schedule.isGrandFinal,
      isSurvivalStage: schedule.isSurvivalStage,
      isLastChanceQualifier: schedule.isLastChanceQualifier
    });
    setScheduleToFinishOnSaveId(schedule.id || null);
    setEditingScheduleEntry(null);
    setAdminSubTab("addMatch");
    setActiveTab("admin");
  };

  // Deep-link from a Match Schedule entry's "Edit" (pencil) button into Add New Match Data's own
  // schedule-only mode, instead of Match Schedule having its own separate edit form - one place to
  // create or edit a not-yet-played match, so nothing needs entering twice.
  const [editingScheduleEntry, setEditingScheduleEntry] = useState<ScheduleEntry | null>(null);

  const handleEditScheduleEntry = (schedule: ScheduleEntry) => {
    setEditingScheduleEntry(schedule);
    setMatchPrefill(null);
    setScheduleToFinishOnSaveId(null);
    setAdminSubTab("addMatch");
    setActiveTab("admin");
  };

  // Bumped to force Add New Match Data (the embedded, non-modal instance) to remount with a blank
  // slate on "Back" - simpler and more reliable than resetting each of its many internal fields by
  // hand, and avoids the old behavior of leaving the Admin tab entirely on cancel (landing on
  // Matches, requiring a click back into Admin to get anywhere).
  const [addMatchFormResetKey, setAddMatchFormResetKey] = useState(0);

  // Deep-link from a finished Match Schedule entry down into its posted result in Match Explorer.
  // Matched by league + date, same pairing used everywhere else a schedule is tied to a match.
  const [matchFocusRequest, setMatchFocusRequest] = useState<{ id: string; token: number } | null>(null);

  const handleViewScheduledMatch = (schedule: ScheduleEntry) => {
    const dateStr = isoToGmt7Parts(schedule.scheduledAt)?.date || "";
    // Normalized (trim + case-insensitive): an exact `===` here silently fails to find the match
    // whenever the league name differs by stray whitespace or casing between the two records (see
    // the same fix applied to Match Schedule's "no schedule yet" counter and the auto-finish/
    // auto-delete pairing below), leaving "View Match" a dead click with no visible error.
    const match = matches.find(m => (m.league || "").trim().toLowerCase() === (schedule.league || "").trim().toLowerCase() && m.date === dateStr);
    if (match?.id) setMatchFocusRequest({ id: match.id, token: Date.now() });
  };

  // Deep-link target for the Player Input Panel, set when "Edit" is clicked on an already-posted
  // player stats record from the Player Stats tab.
  const [playerInputTarget, setPlayerInputTarget] = useState<{ league: string; date?: string; week?: string; tournamentWide?: boolean; isGrandFinal?: boolean; isSurvivalStage?: boolean; isLastChanceQualifier?: boolean } | null>(null);

  const handleEditPlayerRecord = (league: string, period: { date?: string; week?: string; tournamentWide?: boolean; isGrandFinal?: boolean; isSurvivalStage?: boolean; isLastChanceQualifier?: boolean }) => {
    setPlayerInputTarget({ league, ...period });
    setAdminSubTab("playerInput");
    setActiveTab("admin");
  };

  // Toast notifications
  const [toast, setToast] = useState<{ message: string; type: "success" | "error" | "info" } | null>(null);

  const showToast = (message: string, type: "success" | "error" | "info" = "success") => {
    setToast({ message, type });
    setTimeout(() => {
      setToast(null);
    }, 4000);
  };

  // Remove sessions created by older versions so an update also locks open tabs.
  useEffect(() => {
    localStorage.removeItem("pubgm_db_token");
    localStorage.removeItem("pubgm_action_verified");
    localStorage.removeItem("pubgm_action_password");
  }, []);

  // Sync dark mode class
  useEffect(() => {
    const root = window.document.documentElement;
    if (isDarkMode) {
      root.classList.remove("light");
      localStorage.setItem("pubgm_db_theme", "dark");
    } else {
      root.classList.add("light");
      localStorage.setItem("pubgm_db_theme", "light");
    }
  }, [isDarkMode]);

  const handleLogin = (newToken: string) => {
    setToken(newToken);
    showToast("Welcome! Successfully signed in to the database.", "success");
  };

  const handleLogout = () => {
    setToken(null);
    setActionPasswordVerified(false);
    setActionPassword("");
    showToast("Successfully signed out.", "info");
  };

  // Before the Player Stats migration, daily/weekly/tournament-wide stats were saved as rows in
  // `matches` itself (matchCode "DAILY_...") rather than in the dedicated `daily_stats` table. That
  // migration copied them into `daily_stats` but the old rows were never deleted from `matches`, so
  // the same stats get double-counted (once as a "match" here, once as Daily Stats) until they are.
  // Filtering them out client-side keeps counts correct regardless of whether that cleanup has run.
  const filterOutLeftoverDailyStatMatches = (data: Match[]): Match[] =>
    data.filter(m => !(m.matchCode || "").startsWith("DAILY_"));

  // Fetch match and roster data from API
  const fetchMatches = async () => {
    if (!token) return;
    setIsLoadingMatches(true);
    try {
      if (clientDb.getIsStatic()) {
        const data = await clientDb.getMatches();
        setMatches(filterOutLeftoverDailyStatMatches(data));
        return;
      }
      const res = await fetch("/api/matches", {
        headers: {
          Authorization: `Bearer ${token}`
        }
      });
      if (res.ok) {
        const data = await res.json();
        setMatches(filterOutLeftoverDailyStatMatches(data));
        setSupabaseSetupNeeded(false);
      } else {
        const errData = await res.json().catch(() => ({}));
        if (res.status === 401) {
          handleLogout();
        } else {
          if (errData.error === "DATABASE_SETUP_NEEDED" || (errData.error && (errData.error.includes("schema cache") || errData.error.includes("relation")))) {
            setSupabaseSetupNeeded(true);
          }
          showToast(errData.message || errData.error || "Failed to load match data.", "error");
        }
      }
    } catch (err: any) {
      try {
        const data = await clientDb.getMatches();
        setMatches(filterOutLeftoverDailyStatMatches(data));
      } catch (clientErr: any) {
        showToast("Network error: " + err.message, "error");
      }
    } finally {
      setIsLoadingMatches(false);
    }
  };

  const fetchRoster = async () => {
    if (!token) return;
    setIsLoadingRoster(true);
    try {
      if (clientDb.getIsStatic()) {
        const data = await clientDb.getRoster();
        setRoster(data);
        return;
      }
      const res = await fetch("/api/roster", {
        headers: {
          Authorization: `Bearer ${token}`
        }
      });
      if (res.ok) {
        const data = await res.json();
        setRoster(data);
        setSupabaseSetupNeeded(false);
      } else {
        const errData = await res.json().catch(() => ({}));
        if (errData.error === "DATABASE_SETUP_NEEDED" || (errData.error && (errData.error.includes("schema cache") || errData.error.includes("relation")))) {
          setSupabaseSetupNeeded(true);
        }
      }
    } catch (err: any) {
      try {
        const data = await clientDb.getRoster();
        setRoster(data);
      } catch (clientErr: any) {
        console.error("Error fetching roster:", err);
      }
    } finally {
      setIsLoadingRoster(false);
    }
  };

  const fetchSchedules = async () => {
    if (!token) return;
    setIsLoadingSchedules(true);
    try {
      if (clientDb.getIsStatic()) {
        const data = await clientDb.getSchedules();
        setSchedules(data);
        return;
      }
      const res = await fetch("/api/schedules", {
        headers: {
          Authorization: `Bearer ${token}`
        }
      });
      if (res.ok) {
        const data = await res.json();
        setSchedules(data);
      } else {
        const errData = await res.json().catch(() => ({}));
        if (errData.error !== "DATABASE_SETUP_NEEDED") {
          console.error("Error fetching schedules:", errData);
        }
      }
    } catch (err: any) {
      try {
        const data = await clientDb.getSchedules();
        setSchedules(data);
      } catch (clientErr: any) {
        console.error("Error fetching schedules:", err);
      }
    } finally {
      setIsLoadingSchedules(false);
    }
  };

  // The Player Input Panel always looks up and updates the existing row for a league+period (see
  // its foundDailyMatch lookup) rather than inserting a new one, so two rows should never share a
  // league+matchCode through normal use. If the matches->daily_stats migration's INSERT...SELECT
  // step ever ran more than once, though, every pre-migration period would have been copied in
  // twice - silently doubling every number for that period. Keeping only the highest-id (most
  // recently inserted) copy per league+matchCode neutralizes that regardless of cause.
  const dedupeDailyStats = (data: DailyStatsEntry[]): DailyStatsEntry[] => {
    const byKey = new Map<string, DailyStatsEntry>();
    data.forEach(d => {
      const key = `${(d.league || "").trim().toLowerCase()}__${d.matchCode}`;
      const existing = byKey.get(key);
      if (!existing || Number(d.id) > Number(existing.id)) {
        byKey.set(key, d);
      }
    });
    return Array.from(byKey.values());
  };

  const fetchDailyStats = async () => {
    if (!token) return;
    try {
      if (clientDb.getIsStatic()) {
        const data = await clientDb.getDailyStats();
        setDailyStats(dedupeDailyStats(data));
        return;
      }
      const res = await fetch("/api/daily-stats", {
        headers: {
          Authorization: `Bearer ${token}`
        }
      });
      if (res.ok) {
        const data = await res.json();
        setDailyStats(dedupeDailyStats(data));
      } else {
        const errData = await res.json().catch(() => ({}));
        if (errData.error !== "DATABASE_SETUP_NEEDED") {
          console.error("Error fetching daily stats:", errData);
        }
      }
    } catch (err: any) {
      try {
        const data = await clientDb.getDailyStats();
        setDailyStats(dedupeDailyStats(data));
      } catch (clientErr: any) {
        console.error("Error fetching daily stats:", err);
      }
    }
  };

  useEffect(() => {
    if (token) {
      fetchMatches();
      fetchRoster();
      fetchTournaments();
      fetchSchedules();
      fetchDailyStats();
    }
  }, [token]);

  // Admin Verification check
  const verifyActionPassword = async (password: string): Promise<boolean> => {
    try {
      if (clientDb.getIsStatic()) {
        const isValid = await clientDb.verifyActionPassword(password);
        if (isValid) {
          setActionPasswordVerified(true);
          setActionPassword(password);
          showToast("Verification successful! Admin mode active.", "success");
          return true;
        }
        return false;
      }
      const res = await fetch("/api/verify-action", {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ password })
      });
      if (res.ok) {
        setActionPasswordVerified(true);
        setActionPassword(password);
        showToast("Verification successful! Admin mode active.", "success");
        return true;
      }
      return false;
    } catch (err) {
      const isValid = await clientDb.verifyActionPassword(password);
      if (isValid) {
        setActionPasswordVerified(true);
        setActionPassword(password);
        showToast("Verification successful! Admin mode active.", "success");
        return true;
      }
      return false;
    }
  };

  // Save/Edit Matches
  const handleSaveMatch = async (matchData: Match) => {
    const isEdit = !!matchData.id;
    const successMessage = isEdit ? "Successfully updated the match record." : "Successfully added a new match to the database.";

    const saveViaClientDb = async () => {
      if (isEdit) {
        await clientDb.updateMatch(matchData.id!, matchData);
      } else {
        await clientDb.addMatch(matchData);
      }
    };

    // Runs after every successful save path below. When this was a brand-new (not edited) match
    // result, keeps Match Schedule in sync with it so the admin never has to separately remember
    // to go set one up - whether that's finishing the schedule entry explicitly linked via "Enter
    // Match Result" (scheduleToFinishOnSaveId), finishing any other not-yet-finished schedule entry
    // for the same league and date (the result was entered directly instead, e.g. via the same-
    // form "hasn't happened yet" toggle turned off), or - if genuinely no schedule entry exists yet
    // for it at all, e.g. a result for an already-played match entered straight in without ever
    // being scheduled ahead of time - creating one now (already Finished), the same shape Match
    // Schedule's own "Buat Jadwal" backfill button produces, instead of leaving it to show up in
    // that backfill's "no schedule yet" list until someone notices and clicks it manually.
    const finalizeSuccess = () => {
      setEditingMatch(null);
      fetchMatches();
      setActiveTab("matches");
      if (!isEdit) {
        // Normalized league comparison (trim + case-insensitive) - an exact `===` here used to mean
        // a match result entered directly (not via the "Enter Match Result" button, so
        // scheduleToFinishOnSaveId is unset) would silently fail to auto-finish its schedule entry
        // whenever the two records' league strings differed by stray whitespace or casing, leaving
        // that entry stuck looking "ongoing" in Match Schedule forever.
        const linkedSchedule = scheduleToFinishOnSaveId
          ? schedules.find(s => s.id === scheduleToFinishOnSaveId)
          : schedules.find(s => !s.isFinished && (s.league || "").trim().toLowerCase() === (matchData.league || "").trim().toLowerCase() && isoToGmt7Parts(s.scheduledAt)?.date === matchData.date);
        if (linkedSchedule) {
          handleSaveSchedule({ ...linkedSchedule, isFinished: true });
        } else {
          // No time was necessarily entered on the result (Time is optional there) - falls back to
          // the same default Match Schedule's own bulk backfill uses for exactly this situation.
          const scheduledAtIso = gmt7ToIso(matchData.date, matchData.time || "18:00");
          if (scheduledAtIso) {
            handleSaveSchedule({
              league: matchData.league || "",
              matchCode: matchData.matchCode,
              gameNo: matchData.gameNo,
              teams: matchData.teams.map(t => t.name),
              map: matchData.map,
              scheduledAt: scheduledAtIso,
              liveLink: matchData.liveLink || "",
              isFinished: true,
              isGrandFinal: matchData.isGrandFinal,
              isSurvivalStage: matchData.isSurvivalStage,
              isLastChanceQualifier: matchData.isLastChanceQualifier
            });
          }
        }
        setScheduleToFinishOnSaveId(null);
      }
    };

    try {
      if (clientDb.getIsStatic()) {
        await saveViaClientDb();
        showToast(successMessage, "success");
        finalizeSuccess();
        return;
      }

      const tokenToUse = actionPassword || token || "";
      const url = isEdit ? `/api/matches/${matchData.id}` : "/api/matches";
      const method = isEdit ? "PUT" : "POST";
      const res = await fetch(url, {
        method,
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${tokenToUse}`
        },
        body: JSON.stringify(matchData)
      });

      if (!res.ok) {
        const errData = await res.json().catch(() => ({}));
        throw new Error(errData.error || "Failed to save the match.");
      }

      showToast(successMessage, "success");
      finalizeSuccess();
    } catch (err: any) {
      // Failures are re-thrown after this so callers (AddMatchForm, PlayerInputPanel) know the
      // save genuinely failed instead of showing a false "success" message of their own.
      try {
        await saveViaClientDb();
        showToast(`${successMessage} (Static fallback).`, "success");
        finalizeSuccess();
      } catch (dbErr: any) {
        showToast("Error saving match: " + err.message, "error");
        throw err;
      }
    }
  };

  // Delete Match
  const handleDeleteMatch = async (id: string) => {
    // If this match corresponds to a schedule entry (same league + date), delete that too so it
    // doesn't linger in Match Schedule after the match it represents is gone.
    const deletedMatch = matches.find(m => m.id === id);
    // Normalized (trim + case-insensitive) - see handleViewScheduledMatch/handleSaveMatch above for
    // why an exact `===` here is unreliable.
    const matchingSchedule = deletedMatch
      ? schedules.find(s => (s.league || "").trim().toLowerCase() === (deletedMatch.league || "").trim().toLowerCase() && isoToGmt7Parts(s.scheduledAt)?.date === deletedMatch.date)
      : undefined;

    try {
      if (clientDb.getIsStatic()) {
        await clientDb.deleteMatch(id);
        showToast("Match record permanently deleted.", "success");
        fetchMatches();
        if (matchingSchedule?.id) await handleDeleteSchedule(matchingSchedule.id);
        return;
      }
      const tokenToUse = actionPassword || token || "";
      const res = await fetch(`/api/matches/${id}?password=${encodeURIComponent(tokenToUse)}`, {
        method: "DELETE",
        headers: {
          Authorization: `Bearer ${tokenToUse}`,
          "x-password": tokenToUse
        }
      });
      if (res.ok) {
        showToast("Match record permanently deleted.", "success");
        fetchMatches();
        if (matchingSchedule?.id) await handleDeleteSchedule(matchingSchedule.id);
      } else {
        const errData = await res.json();
        if (res.status === 401) {
          setActionPasswordVerified(false);
          setActionPassword("");
        }
        showToast(errData.error || "Failed to delete the match.", "error");
      }
    } catch (err: any) {
      try {
        await clientDb.deleteMatch(id);
        showToast("Match record permanently deleted.", "success");
        fetchMatches();
        if (matchingSchedule?.id) await handleDeleteSchedule(matchingSchedule.id);
      } catch (dbErr: any) {
        showToast("Error deleting match: " + err.message, "error");
      }
    }
  };

  // Save / Edit Schedule Entry
  const handleSaveSchedule = async (scheduleData: ScheduleEntry) => {
    const isEdit = !!scheduleData.id;

    const saveViaClientDb = async () => {
      if (isEdit) {
        await clientDb.updateSchedule(scheduleData.id!, scheduleData);
      } else {
        await clientDb.addSchedule(scheduleData);
      }
    };

    try {
      if (clientDb.getIsStatic()) {
        await saveViaClientDb();
        showToast(isEdit ? "Schedule updated." : "Schedule added.", "success");
        fetchSchedules();
        return;
      }

      const tokenToUse = actionPassword || token || "";
      const url = isEdit ? `/api/schedules/${scheduleData.id}` : "/api/schedules";
      const method = isEdit ? "PUT" : "POST";
      const res = await fetch(url, {
        method,
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${tokenToUse}`
        },
        body: JSON.stringify(scheduleData)
      });

      if (!res.ok) {
        const errData = await res.json().catch(() => ({}));
        throw new Error(errData.error || "Failed to save the schedule.");
      }

      showToast(isEdit ? "Schedule updated." : "Schedule added.", "success");
      fetchSchedules();
    } catch (err: any) {
      try {
        await saveViaClientDb();
        showToast(`${isEdit ? "Schedule updated" : "Schedule added"} (Static fallback).`, "success");
        fetchSchedules();
      } catch (dbErr: any) {
        showToast("Error saving schedule: " + err.message, "error");
        throw err;
      }
    }
  };

  // Delete Schedule Entry
  const handleDeleteSchedule = async (id: string) => {
    try {
      if (clientDb.getIsStatic()) {
        await clientDb.deleteSchedule(id);
        showToast("Schedule entry deleted.", "success");
        fetchSchedules();
        return;
      }
      const tokenToUse = actionPassword || token || "";
      const res = await fetch(`/api/schedules/${id}?password=${encodeURIComponent(tokenToUse)}`, {
        method: "DELETE",
        headers: {
          Authorization: `Bearer ${tokenToUse}`,
          "x-password": tokenToUse
        }
      });
      if (res.ok) {
        showToast("Schedule entry deleted.", "success");
        fetchSchedules();
      } else {
        const errData = await res.json();
        showToast(errData.error || "Failed to delete the schedule entry.", "error");
      }
    } catch (err: any) {
      try {
        await clientDb.deleteSchedule(id);
        showToast("Schedule entry deleted.", "success");
        fetchSchedules();
      } catch (dbErr: any) {
        showToast("Error deleting schedule: " + err.message, "error");
      }
    }
  };

  // Save / Edit a Player Input Panel (Daily Stats) entry
  const handleSaveDailyStats = async (entryData: DailyStatsEntry) => {
    const isEdit = !!entryData.id;

    const saveViaClientDb = async () => {
      if (isEdit) {
        await clientDb.updateDailyStats(entryData.id!, entryData);
      } else {
        await clientDb.addDailyStats(entryData);
      }
    };

    try {
      if (clientDb.getIsStatic()) {
        await saveViaClientDb();
        showToast("All daily player stats saved successfully!", "success");
        fetchDailyStats();
        return;
      }

      const tokenToUse = actionPassword || token || "";
      const url = isEdit ? `/api/daily-stats/${entryData.id}` : "/api/daily-stats";
      const method = isEdit ? "PUT" : "POST";
      const res = await fetch(url, {
        method,
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${tokenToUse}`
        },
        body: JSON.stringify(entryData)
      });

      if (!res.ok) {
        const errData = await res.json().catch(() => ({}));
        throw new Error(errData.error || "Failed to save the daily stats entry.");
      }

      showToast("All daily player stats saved successfully!", "success");
      fetchDailyStats();
    } catch (err: any) {
      // Failure is re-thrown after this so PlayerInputPanel knows the save genuinely failed
      // instead of showing a false "success" message of its own.
      try {
        await saveViaClientDb();
        showToast("All daily player stats saved successfully! (Static fallback).", "success");
        fetchDailyStats();
      } catch (dbErr: any) {
        showToast("Failed to save stats: " + err.message, "error");
        throw err;
      }
    }
  };

  // Deletes one whole Daily Stats record (a single day/week/tournament-wide period entry, every
  // player in it) - distinct from handleDeletePlayerStats, which removes one player across every
  // period. Used from Player Input Panel when an existing record is loaded for editing.
  const handleDeleteDailyStats = async (id: string) => {
    try {
      if (clientDb.getIsStatic()) {
        await clientDb.deleteDailyStats(id);
        showToast("Daily stats record deleted.", "success");
        fetchDailyStats();
        return;
      }
      const tokenToUse = actionPassword || token || "";
      const res = await fetch(`/api/daily-stats/${id}?password=${encodeURIComponent(tokenToUse)}`, {
        method: "DELETE",
        headers: {
          Authorization: `Bearer ${tokenToUse}`,
          "x-password": tokenToUse
        }
      });
      if (res.ok) {
        showToast("Daily stats record deleted.", "success");
        fetchDailyStats();
      } else {
        const errData = await res.json();
        showToast(errData.error || "Failed to delete the daily stats record.", "error");
      }
    } catch (err: any) {
      try {
        await clientDb.deleteDailyStats(id);
        showToast("Daily stats record deleted.", "success");
        fetchDailyStats();
      } catch (dbErr: any) {
        showToast("Error deleting daily stats record: " + err.message, "error");
      }
    }
  };

  // Save / Edit Roster Player
  const handleSaveRosterPlayer = async (player: RosterPlayer) => {
    try {
      if (clientDb.getIsStatic()) {
        await clientDb.saveRosterPlayer(player);
        showToast("Roster successfully updated.", "success");
        fetchRoster();
        return;
      }
      const pass = ACTION_PASSWORD_LOCAL();
      const res = await fetch("/api/roster", {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          password: pass,
          player
        })
      });
      if (res.ok) {
        showToast("Roster successfully updated.", "success");
        fetchRoster();
      } else {
        const errData = await res.json();
        showToast(errData.error || "Failed to save the roster player.", "error");
      }
    } catch (err: any) {
      try {
        await clientDb.saveRosterPlayer(player);
        showToast("Roster successfully updated.", "success");
        fetchRoster();
      } catch (dbErr: any) {
        showToast("Error saving roster: " + err.message, "error");
      }
    }
  };

  // Delete Roster Player
  const handleDeleteRosterPlayer = async (id: string) => {
    try {
      if (clientDb.getIsStatic()) {
        await clientDb.deleteRosterPlayer(id);
        showToast("Player successfully removed from the roster.", "success");
        fetchRoster();
        return;
      }
      const pass = ACTION_PASSWORD_LOCAL();
      const res = await fetch(`/api/roster/${id}?password=${encodeURIComponent(pass)}`, {
        method: "DELETE",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${pass}`,
          "x-password": pass
        },
        body: JSON.stringify({
          password: pass
        })
      });
      if (res.ok) {
        showToast("Player successfully removed from the roster.", "success");
        fetchRoster();
      } else {
        const errData = await res.json();
        if (res.status === 401) {
          setActionPasswordVerified(false);
          setActionPassword("");
        }
        showToast(errData.error || "Failed to delete the roster player.", "error");
      }
    } catch (err: any) {
      try {
        await clientDb.deleteRosterPlayer(id);
        showToast("Player successfully removed from the roster.", "success");
        fetchRoster();
      } catch (dbErr: any) {
        showToast("Error deleting roster: " + err.message, "error");
      }
    }
  };

  // Delete Player Stats across both real match results and Daily Stats entries
  const handleDeletePlayerStats = async (playerName: string, teamName?: string) => {
    try {
      const targetName = playerName.trim().toLowerCase();
      const targetTeam = teamName?.trim().toLowerCase();
      const matchesPlayer = (p: any, t: any) =>
        p.name.trim().toLowerCase() === targetName &&
        (!targetTeam || (t.name || "").trim().toLowerCase() === targetTeam);
      const containsPlayer = (m: { teams?: any[] }) =>
        (m.teams || []).some(t =>
          (t.players || []).some((p: any) => matchesPlayer(p, t))
        );
      const stripPlayer = (teams: any[]) => teams.map(t => ({
        ...t,
        players: (t.players || []).filter((p: any) => !matchesPlayer(p, t))
      }));

      const matchesToUpdate = matches.filter(containsPlayer);
      const dailyStatsToUpdate = dailyStats.filter(containsPlayer);

      if (matchesToUpdate.length === 0 && dailyStatsToUpdate.length === 0) {
        showToast(`No match records found for player ${playerName}.`, "info");
        return;
      }

      const tokenToUse = actionPassword || token || "";

      // Each record's update is independent (different match/daily-stats ids), so they run
      // concurrently instead of one round-trip at a time.
      await Promise.all(matchesToUpdate.map(m => {
        const updatedMatch: Match = { ...m, teams: stripPlayer(m.teams || []) };
        if (clientDb.getIsStatic()) {
          return clientDb.updateMatch(m.id!, updatedMatch);
        }
        return fetch(`/api/matches/${m.id}`, {
          method: "PUT",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${tokenToUse}`
          },
          body: JSON.stringify(updatedMatch)
        });
      }));

      await Promise.all(dailyStatsToUpdate.map(d => {
        const updatedEntry: DailyStatsEntry = { ...d, teams: stripPlayer(d.teams || []) };
        if (clientDb.getIsStatic()) {
          return clientDb.updateDailyStats(d.id!, updatedEntry);
        }
        return fetch(`/api/daily-stats/${d.id}`, {
          method: "PUT",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${tokenToUse}`
          },
          body: JSON.stringify(updatedEntry)
        });
      }));

      showToast(`Successfully deleted all stats for player ${playerName} permanently.`, "success");
      fetchMatches();
      fetchDailyStats();
    } catch (err: any) {
      showToast("Failed to delete player stats: " + err.message, "error");
    }
  };

  // Player Stats and Comparisons need real match results and Daily Stats entries aggregated
  // together (one is per-match placement/kills, the other is pre-aggregated per-period player
  // stats) - reconstructed here as a single view so those two components' existing aggregation
  // logic (which branches on `isDailyStats`) doesn't need to know the two now live in separate
  // tables. Real match results (`matches`) are unaffected and never carry this synthetic flag.
  const matchesWithDailyStats: Match[] = useMemo(() => [
    ...matches,
    ...dailyStats.map((d): Match => ({
      ...d,
      map: "All Maps",
      isDailyStats: true
    }))
  ], [matches, dailyStats]);

  const ACTION_PASSWORD_LOCAL = (): string => {
    return actionPassword;
  };

  // Edit action triggers form populator
  const handleTriggerEditMatch = (match: Match) => {
    setEditingMatch(match);
  };

  if (!token) {
    return <AuthScreen onLogin={handleLogin} isDarkMode={isDarkMode} setIsDarkMode={setIsDarkMode} />;
  }

  return (
    <div className={`min-h-screen transition-colors duration-200 selection:bg-amber-500/30 font-sans ${
      isDarkMode ? "bg-[#0b0f19] text-slate-100" : "bg-slate-50 text-slate-900"
    }`}>
      {/* HEADER SECTION */}
      <header className={`sticky top-0 z-50 backdrop-blur-md transition-all ${
        isDarkMode ? "bg-[#0b0f19]/85 border-b border-slate-900" : "bg-white/85 shadow-sm"
      }`}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <img
              src="https://www.pubgmobile.com/images/event/brandassets/down-logo1.png"
              alt="PUBG Mobile"
              className="h-10 w-10 object-contain"
            />
            <div>
              <h1 className={`font-black font-display text-sm tracking-tight flex items-center gap-1.5 uppercase ${isDarkMode ? "text-slate-100" : "text-slate-950"}`}>
                PUBGM DATABASE
              </h1>
              <p className="text-[10px] text-slate-500 font-mono tracking-wide">LEVEL UP INDONESIA</p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            {/* Theme Toggle */}
            <button
              onClick={() => setIsDarkMode(!isDarkMode)}
              className={`p-2.5 rounded-xl border cursor-pointer transition-all ${
                isDarkMode ? "bg-slate-900 border-slate-800 text-slate-400 hover:text-white" : "bg-slate-200/60 border-slate-200 text-slate-600 hover:bg-slate-200"
              }`}
            >
              {isDarkMode ? <Sun className="w-4 h-4" /> : <Moon className="w-4 h-4" />}
            </button>

            {/* Admin Button */}
            <button
              onClick={() => {
                setActiveTab("admin");
                if (editingMatch) setEditingMatch(null);
              }}
              className={`p-2.5 rounded-xl border font-bold text-xs cursor-pointer transition-all flex items-center gap-1.5 ${
                activeTab === "admin"
                  ? "bg-amber-500 border-amber-400 text-slate-950"
                  : isDarkMode
                    ? "bg-slate-900 border-slate-800 text-slate-400 hover:text-white"
                    : "bg-slate-200/60 border-slate-200 text-slate-600 hover:bg-slate-200"
              }`}
            >
              <span className="font-mono">Admin</span>
            </button>

            {/* Logout button */}
            <button
              onClick={handleLogout}
              className={`p-2.5 rounded-xl border font-semibold text-xs cursor-pointer transition-all flex items-center gap-1.5 ${
                isDarkMode ? "bg-slate-900 border-slate-800 text-slate-400 hover:text-white" : "bg-slate-200/60 border-slate-200 text-slate-600 hover:bg-slate-200"
              }`}
            >
              <LogOut className="w-4 h-4 shrink-0" />
              <span className="hidden sm:inline font-mono">Sign Out</span>
            </button>
          </div>
        </div>
      </header>

      {/* CORE NAVIGATION NAVIGATION TABS */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-6">
        <div className={`p-4 rounded-3xl border transition-all ${
          isDarkMode ? "bg-slate-900/30 border-slate-900" : "bg-white border-slate-200 shadow-sm"
        }`}>
          <div className="flex items-center gap-1.5 overflow-x-auto pb-1 scrollbar-thin whitespace-nowrap">
            {[
              { id: "matches", label: "Match Results", icon: Activity },
              { id: "tournamentStandings", label: "Match Standings", icon: Trophy },
              { id: "pmgcRace", label: "PMGC Race", icon: Globe2 },
              { id: "playerStats", label: "Player Stats", icon: Users },
              { id: "rosterManager", label: "Rosters", icon: Award },
              { id: "headTohead", label: "Comparisons", icon: ArrowRightLeft },
              { id: "dropZones", label: "Drop Zones", icon: MapPin }
            ].map((tab) => {
              const Icon = tab.icon;
              const isActive = activeTab === tab.id;
              return (
                <button
                  key={tab.id}
                  onClick={() => {
                    setActiveTab(tab.id);
                    if (editingMatch) setEditingMatch(null);
                  }}
                  className={`px-4 py-2 rounded-xl font-mono text-xs font-bold transition-all flex items-center gap-2 shrink-0 cursor-pointer border ${
                    isActive
                      ? "bg-amber-500 text-slate-950 border-amber-400 shadow-md shadow-amber-500/10 font-extrabold"
                      : isDarkMode
                        ? "bg-slate-950/40 border-slate-850 text-slate-400 hover:text-white hover:bg-slate-800/40"
                        : "bg-slate-100 border-slate-200 text-slate-600 hover:text-slate-900 hover:bg-white"
                  }`}
                >
                  <Icon className="w-3.5 h-3.5 shrink-0" />
                  <span>{tab.label}</span>
                </button>
              );
            })}
          </div>
        </div>
      </div>

      {/* MAIN CONTAINER CONTENT */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {supabaseSetupNeeded && (
          <div className={`mb-8 p-6 rounded-3xl border transition-all ${
            isDarkMode ? "bg-amber-950/20 border-amber-500/30 text-amber-100" : "bg-amber-50 border-amber-200 text-amber-900"
          }`}>
            <div className="flex flex-col lg:flex-row gap-5 items-start justify-between">
              <div className="space-y-2 flex-1">
                <h3 className="font-bold text-base flex items-center gap-2">
                  <Trophy className="w-5 h-5 text-amber-500 animate-pulse" />
                  Supabase Database Setup Required
                </h3>
                <p className="text-xs text-slate-400 leading-relaxed">
                  The <code className="font-mono bg-slate-900 px-1 py-0.5 rounded text-amber-400">matches</code>, <code className="font-mono bg-slate-900 px-1 py-0.5 rounded text-amber-400">roster</code>, <code className="font-mono bg-slate-900 px-1 py-0.5 rounded text-amber-400">schedules</code>, or <code className="font-mono bg-slate-900 px-1 py-0.5 rounded text-amber-400">daily_stats</code> table was not found in your Supabase database.
                  Copy the SQL script below, run it in your Supabase dashboard's <strong>SQL Editor</strong>, then refresh this page.
                </p>
                <div className="mt-4 relative bg-slate-950 p-4 rounded-xl border border-slate-850 font-mono text-[11px] text-slate-300 max-h-48 overflow-y-auto whitespace-pre select-all">
                  {SUPABASE_SETUP_SQL}
                </div>
              </div>
              <button
                onClick={() => {
                  navigator.clipboard.writeText(SUPABASE_SETUP_SQL);
                  showToast("SQL script copied!", "success");
                }}
                className="px-4 py-2.5 rounded-xl bg-amber-500 text-slate-950 font-mono text-xs font-bold hover:bg-amber-400 cursor-pointer shadow-md shadow-amber-500/10 shrink-0 self-start lg:self-center"
              >
                Copy SQL Script
              </button>
            </div>
          </div>
        )}

        {/* Matches lists logs tab */}
        {activeTab === "matches" && (
          <div className="space-y-8">
            <MatchSchedule
              schedules={schedules}
              isLoading={isLoadingSchedules}
              onSaveSchedule={handleSaveSchedule}
              onDeleteSchedule={handleDeleteSchedule}
              onEnterResults={handleEnterScheduleResults}
              onEditSchedule={handleEditScheduleEntry}
              onViewMatch={handleViewScheduledMatch}
              matches={matches}
              isDarkMode={isDarkMode}
              actionPasswordVerified={actionPasswordVerified}
            />
            <MatchExplorer
              matches={matches}
              isLoading={isLoadingMatches}
              onDeleteMatch={handleDeleteMatch}
              onEditMatch={handleTriggerEditMatch}
              isDarkMode={isDarkMode}
              actionPasswordVerified={actionPasswordVerified}
              focusRequest={matchFocusRequest}
            />
          </div>
        )}

        {/* Tournament Standings tab */}
        {activeTab === "tournamentStandings" && (
          <TournamentStandings matches={matches} isDarkMode={isDarkMode} tournaments={tournaments} />
        )}

        {/* PMGC Race tab - cross-tournament points race for a given year */}
        {activeTab === "pmgcRace" && (
          <PmgcRace matches={matches} isDarkMode={isDarkMode} tournaments={tournaments} />
        )}

        {/* Player Stats Dashboard tab */}
        {activeTab === "playerStats" && (
          <PlayerStats
            matches={matchesWithDailyStats}
            isDarkMode={isDarkMode}
            actionPasswordVerified={actionPasswordVerified}
            verifyActionPassword={verifyActionPassword}
            onDeletePlayerStats={handleDeletePlayerStats}
            tournaments={tournaments}
            roster={roster}
            onEditPlayerRecord={handleEditPlayerRecord}
          />
        )}

        {/* Head-to-Head Comparison tab */}
        {activeTab === "headTohead" && (
          <HeadToHead matches={matchesWithDailyStats} isDarkMode={isDarkMode} tournaments={tournaments} roster={roster} />
        )}

        {/* Drop zone simulator tab */}
        {activeTab === "dropZones" && (
          <DropZoneSimulator
            isDarkMode={isDarkMode}
            tournaments={tournaments}
            roster={roster}
          />
        )}

        {/* Roster management database tab */}
        {activeTab === "rosterManager" && (
          <RosterManager
            roster={roster}
            matches={matches}
            isLoading={isLoadingRoster}
            onSavePlayer={handleSaveRosterPlayer}
            onDeletePlayer={handleDeleteRosterPlayer}
            isDarkMode={isDarkMode}
            actionPasswordVerified={actionPasswordVerified}
            tournaments={tournaments}
            onUpdateTournaments={handleUpdateTournaments}
          />
        )}

        {/* Unified Admin Panel */}
        {activeTab === "admin" && (
          !actionPasswordVerified ? (
            <div className={`p-8 rounded-3xl max-w-sm mx-auto text-center font-mono my-12 transition-all ${
              isDarkMode ? "bg-slate-900/60 border border-slate-800" : "bg-white shadow-xl shadow-slate-100/80"
            }`}>
              <div className="inline-flex p-4 rounded-3xl bg-amber-500/10 text-amber-500 mb-4 animate-bounce">
                <Lock className="w-6 h-6" />
              </div>
              <h3 className={`text-base font-bold uppercase tracking-tight ${isDarkMode ? "text-slate-100" : "text-slate-900"}`}>Access Restricted</h3>
              <p className="text-[10px] text-slate-400 mt-2 mb-6 leading-relaxed uppercase">
                This page requires the action password to access.
              </p>
              <form onSubmit={async (e) => {
                e.preventDefault();
                const formEl = e.currentTarget;
                const inputEl = formEl.elements.namedItem("actionPassword") as HTMLInputElement;
                const isOk = await verifyActionPassword(inputEl.value);
                if (!isOk) {
                  showToast("Incorrect action password!", "error");
                }
              }} className="space-y-4">
                <input
                  type="password"
                  name="actionPassword"
                  placeholder="Action Password"
                  className={`w-full rounded-xl py-2.5 px-4 text-center text-sm font-mono focus:outline-none focus:ring-1 focus:ring-amber-500 transition-all ${
                    isDarkMode 
                      ? "bg-slate-950 border border-slate-800 text-slate-100" 
                      : "bg-slate-100 text-slate-900"
                  }`}
                  required
                />
                <button
                  type="submit"
                  className="w-full py-2.5 px-4 rounded-xl bg-amber-500 hover:bg-amber-400 active:bg-amber-600 text-slate-950 font-bold text-xs tracking-wide transition-all shadow-lg cursor-pointer"
                >
                  UNLOCK ACCESS
                </button>
              </form>
            </div>
          ) : (
            <div className="space-y-6">
              {/* Internal Sub-Tabs for Admin Console */}
              <div className={`p-3 rounded-2xl border flex flex-wrap gap-2 transition-all ${
                isDarkMode ? "bg-slate-950 border-slate-850" : "bg-slate-50 border-slate-200"
              }`}>
                <button
                  type="button"
                  onClick={() => setAdminSubTab("addMatch")}
                  className={`px-4 py-2 text-xs font-bold font-mono rounded-xl transition-all cursor-pointer border flex items-center gap-1.5 ${
                    adminSubTab === "addMatch"
                      ? "bg-amber-500 border-amber-400 text-slate-950 shadow-md"
                      : isDarkMode
                        ? "bg-slate-900 border-slate-800 text-slate-400 hover:text-white"
                        : "bg-white border-slate-200 text-slate-600 hover:text-slate-900"
                  }`}
                >
                  <PlusCircle className="w-3.5 h-3.5 shrink-0" />
                  <span>ADD NEW MATCH DATA</span>
                </button>
                <button
                  type="button"
                  onClick={() => setAdminSubTab("playerInput")}
                  className={`px-4 py-2 text-xs font-bold font-mono rounded-xl transition-all cursor-pointer border flex items-center gap-1.5 ${
                    adminSubTab === "playerInput"
                      ? "bg-amber-500 border-amber-400 text-slate-950 shadow-md"
                      : isDarkMode
                        ? "bg-slate-900 border-slate-800 text-slate-400 hover:text-white"
                        : "bg-white border-slate-200 text-slate-600 hover:text-slate-900"
                  }`}
                >
                  <Users className="w-3.5 h-3.5 shrink-0" />
                  <span>ADD NEW PLAYER DATA</span>
                </button>
              </div>

              {adminSubTab === "playerInput" ? (
                <PlayerInputPanel
                  matches={matches}
                  dailyStats={dailyStats}
                  roster={roster}
                  onSaveDailyStats={handleSaveDailyStats}
                  onDeleteDailyStats={handleDeleteDailyStats}
                  isDarkMode={isDarkMode}
                  tournaments={tournaments}
                  onUpdateTournaments={handleUpdateTournaments}
                  presetSelection={playerInputTarget}
                  onConsumedPresetSelection={() => setPlayerInputTarget(null)}
                />
              ) : (
                <AddMatchForm
                  key={addMatchFormResetKey}
                  onSave={handleSaveMatch}
                  onClose={() => {
                    setEditingMatch(null);
                    setActiveTab("matches");
                    setMatchPrefill(null);
                    setScheduleToFinishOnSaveId(null);
                    setEditingScheduleEntry(null);
                  }}
                  onCancel={() => {
                    setMatchPrefill(null);
                    setScheduleToFinishOnSaveId(null);
                    setEditingScheduleEntry(null);
                    setAddMatchFormResetKey(k => k + 1);
                  }}
                  isDarkMode={isDarkMode}
                  editingMatch={null}
                  matches={matches}
                  dailyStats={dailyStats}
                  tournaments={tournaments}
                  onUpdateTournaments={handleUpdateTournaments}
                  matchPrefill={matchPrefill}
                  onConsumedMatchPrefill={() => setMatchPrefill(null)}
                  onSaveSchedule={handleSaveSchedule}
                  editingSchedule={editingScheduleEntry}
                />
              )}
            </div>
          )
        )}
      </main>

      {/* EDIT MATCH POPUP MODAL */}
      {editingMatch && (
        // No backdrop-blur here on purpose: this modal stays open and gets typed into for a while
        // (unlike the app's short delete-confirm popups), and backdrop-filter forces the browser to
        // keep recompositing the whole blurred viewport on every repaint - heavy enough on the GPU
        // to visibly stutter other GPU-accelerated content on screen (e.g. a video playing elsewhere).
        <div className="fixed inset-0 z-[150] flex items-center justify-center p-4 bg-slate-950/90 overflow-y-auto animate-fadeIn">
          <div className={`w-full max-w-4xl max-h-[90vh] overflow-y-auto rounded-2xl shadow-2xl border ${
            isDarkMode ? "bg-slate-900 border-slate-800" : "bg-white border-slate-200"
          }`}>
            <AddMatchForm
              onSave={handleSaveMatch}
              onClose={() => setEditingMatch(null)}
              isDarkMode={isDarkMode}
              editingMatch={editingMatch}
              matches={matches}
              dailyStats={dailyStats}
              tournaments={tournaments}
              onUpdateTournaments={handleUpdateTournaments}
            />
          </div>
        </div>
      )}

      {/* TOAST ALERT NOTIFICATION COMPONENT */}
      {toast && (
        <div className="fixed bottom-5 right-5 z-[200] max-w-sm animate-fadeIn">
          <div className={`border rounded-xl px-4 py-3.5 shadow-xl font-mono text-xs flex items-center gap-3 ${
            toast.type === "success" 
              ? "bg-emerald-950/95 border-emerald-500 text-emerald-400" 
              : toast.type === "error" 
                ? "bg-red-950/95 border-red-500 text-red-400" 
                : "bg-slate-900/95 border-amber-500 text-amber-500"
          }`}>
            <div className="shrink-0 p-1 bg-white/10 rounded-lg">
              <Activity className="w-4 h-4" />
            </div>
            <p className="font-semibold leading-normal">{toast.message}</p>
          </div>
        </div>
      )}
    </div>
  );
}
